defmodule Mix.Tasks.Ui.Status do
  @shortdoc "Regenerate docs/INVENTORY.md from what is actually on disk"

  @moduledoc """
  The inventory tracker.

  Status is never typed by hand. This task derives it from the files each
  pipeline stage leaves behind, so the tracker cannot drift from reality:

  | Status | Evidence on disk |
  |---|---|
  | `planned` | listed in `registry/INVENTORY.json`, nothing else |
  | `fetched` | a digest in `registry/UPSTREAM.json` |
  | `spec` | `registry/spec/<name>.json` |
  | `generated` | a module in the owning package |
  | `verified` | a passing entry in `registry/VERIFY.json` |

  `registry/INVENTORY.json` holds only the two decisions a person makes: which
  behavior recipe a component uses, and which tier it ships in.

  A component that appears upstream and is missing from the inventory is
  appended with tier 2 and recipe `unassigned`, then reported. New shadcn
  components therefore show up in the tracker on their own.

      mix ui.status
      mix ui.status --check   # exit 1 if docs/INVENTORY.md is stale (for CI)

  """
  use Mix.Task

  import LiveShadcnTools

  @statuses [:planned, :fetched, :spec, :generated, :verified]

  @impl Mix.Task
  def run(argv) do
    Mix.Task.run("app.start")
    {opts, _, _} = OptionParser.parse(argv, strict: [check: :boolean])
    check? = Keyword.get(opts, :check, false)

    inventory = read_json!(registry_path("INVENTORY.json"))
    {components, added} = merge_upstream(inventory["components"])

    if added != [] do
      Mix.shell().info(
        "new upstream components added to the inventory: #{Enum.join(added, ", ")}"
      )

      write_json!(registry_path("INVENTORY.json"), %{inventory | "components" => components})
    end

    rendered = render(inventory, Enum.map(components, &with_status/1))
    path = Path.join([repo_root(), "docs", "INVENTORY.md"])

    cond do
      not check? ->
        write!(path, rendered)
        Mix.shell().info("wrote docs/INVENTORY.md (#{length(components)} components)")

      File.exists?(path) and File.read!(path) == rendered ->
        Mix.shell().info("docs/INVENTORY.md is current")

      true ->
        Mix.raise("docs/INVENTORY.md is stale. Run `mix ui.status`.")
    end
  end

  # A component upstream that nobody has triaged yet must still be visible.
  defp merge_upstream(components) do
    known = MapSet.new(components, & &1["name"])

    upstream =
      case File.exists?(registry_path("UPSTREAM.json")) do
        false ->
          []

        true ->
          registry_path("UPSTREAM.json")
          |> read_json!()
          |> Map.get("files", %{})
          |> Map.keys()
          |> Enum.flat_map(&upstream_entry/1)
          |> Enum.uniq_by(& &1["name"])
      end

    added = Enum.reject(upstream, &MapSet.member?(known, &1["name"]))

    {Enum.sort_by(components ++ added, &{&1["source"], &1["name"]}),
     Enum.map(added, & &1["name"])}
  end

  defp upstream_entry("shadcn/ui/" <> file),
    do: [
      %{
        "name" => Path.basename(file, ".tsx"),
        "source" => "shadcn",
        "recipe" => "unassigned",
        "tier" => 2
      }
    ]

  defp upstream_entry("ai_elements/" <> file),
    do: [
      %{
        "name" => Path.basename(file, ".tsx"),
        "source" => "ai_elements",
        "recipe" => "unassigned",
        "tier" => 2
      }
    ]

  defp upstream_entry(_), do: []

  defp with_status(component) do
    Map.put(component, "status", status_of(component))
  end

  defp status_of(%{"name" => name, "source" => source}) do
    cond do
      verified?(name) -> :verified
      generated?(name, source) -> :generated
      File.exists?(registry_path(["spec", "#{name}.json"])) -> :spec
      fetched?(name, source) -> :fetched
      true -> :planned
    end
  end

  defp fetched?(name, source) do
    path = if source == "shadcn", do: "shadcn/ui/#{name}.tsx", else: "ai_elements/#{name}.tsx"

    case File.exists?(registry_path("UPSTREAM.json")) do
      false -> false
      true -> registry_path("UPSTREAM.json") |> read_json!() |> get_in(["files", path]) != nil
    end
  end

  defp generated?(name, source) do
    module = String.replace(name, "-", "_") <> ".ex"

    package =
      if source == "shadcn",
        do: ["packages", "live_shadcn", "priv", "registry"],
        else: ["packages", "live_ai_elements", "lib", "live_ai_elements", "components"]

    File.exists?(Path.join([repo_root() | package] ++ [module]))
  end

  defp verified?(name) do
    path = registry_path("VERIFY.json")
    File.exists?(path) and get_in(read_json!(path), [name, "pass"]) == true
  end

  defp render(inventory, components) do
    counts = Enum.frequencies_by(components, & &1["status"])
    total = length(components)

    """
    # Inventory

    <!-- Generated by `mix ui.status`. Do not edit by hand. -->

    #{total} components. Status is derived from the files on disk, never typed in.

    #{progress_table(counts, total)}

    ## Recipes

    Eight core recipes cover #{core_coverage(inventory, components)} of #{total} components.
    Only the recipes are written by hand; every component is data.

    #{recipe_table(components)}

    ## shadcn/ui

    #{component_table(components, "shadcn")}

    ## AI Elements

    #{component_table(components, "ai_elements")}
    """
  end

  defp progress_table(counts, total) do
    rows =
      Enum.map_join(@statuses, "\n", fn status ->
        n = Map.get(counts, status, 0)
        "| `#{status}` | #{n} | #{bar(n, total)} |"
      end)

    "| Stage | Components | |\n|---|---:|---|\n" <> rows
  end

  defp bar(n, total) do
    filled = if total == 0, do: 0, else: round(n / total * 24)
    String.duplicate("█", filled) <> String.duplicate("·", 24 - filled)
  end

  defp core_coverage(inventory, components) do
    core = MapSet.new(get_in(inventory, ["recipes", "core"]) || [])
    Enum.count(components, &MapSet.member?(core, &1["recipe"]))
  end

  defp recipe_table(components) do
    core = ~w(disclosure dialog popover listbox menu tabs form-control presentational)

    rows =
      components
      |> Enum.group_by(& &1["recipe"])
      |> Enum.sort_by(fn {recipe, group} -> {recipe not in core, -length(group), recipe} end)
      |> Enum.map_join("\n", fn {recipe, group} ->
        kind = if recipe in core, do: "core", else: "specialist"
        "| `#{recipe}` | #{kind} | #{length(group)} |"
      end)

    "| Recipe | Kind | Components |\n|---|---|---:|\n" <> rows
  end

  defp component_table(components, source) do
    rows =
      components
      |> Enum.filter(&(&1["source"] == source))
      |> Enum.sort_by(&{&1["tier"], &1["name"]})
      |> Enum.map_join("\n", fn c ->
        "| `#{c["name"]}` | #{c["tier"]} | `#{c["recipe"]}` | #{mark(c["status"])} #{c["status"]} |"
      end)

    "| Component | Tier | Recipe | Status |\n|---|---:|---|---|\n" <> rows
  end

  defp mark(:verified), do: "✅"
  defp mark(:generated), do: "🟩"
  defp mark(:spec), do: "🟨"
  defp mark(:fetched), do: "🟦"
  defp mark(:planned), do: "⬜"
end
