defmodule LiveShadcn.UI.Accordion do
  @moduledoc """
  Accordion. Groups all parts of the accordion.

  Generated by `mix ui.gen` from `registry/spec/shadcn/accordion.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.

  | Upstream | Digest |
  |---|---|
  | `shadcn/ui/accordion.tsx` | `3fbd0fd128f9` |
  """

  use Phoenix.Component

  # live-shadcn: upstream facts start
  @upstream_facts %{
    "jsx/Accordion/class/0" => "cn-accordion flex w-full flex-col",
    "jsx/AccordionContent/class/0" => "cn-accordion-content overflow-hidden",
    "jsx/AccordionContent/class/1" =>
      "cn-accordion-content-inner h-(--accordion-panel-height) data-ending-style:h-0 data-starting-style:h-0 [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground [&_p:not(:last-child)]:mb-4",
    "jsx/AccordionItem/class/0" => "cn-accordion-item",
    "jsx/AccordionTrigger/class/0" => "flex",
    "jsx/AccordionTrigger/class/1" =>
      "cn-accordion-trigger group/accordion-trigger relative flex flex-1 items-start justify-between border border-transparent transition-all outline-none aria-disabled:pointer-events-none aria-disabled:opacity-50",
    "jsx/AccordionTrigger/class/2" =>
      "cn-accordion-trigger-icon pointer-events-none shrink-0 group-aria-expanded/accordion-trigger:hidden",
    "jsx/AccordionTrigger/class/3" =>
      "cn-accordion-trigger-icon pointer-events-none hidden shrink-0 group-aria-expanded/accordion-trigger:inline"
  }
  # live-shadcn: upstream facts end
  Module.get_attribute(__MODULE__, :upstream_facts)

  defp upstream_fact(key), do: Map.fetch!(@upstream_facts, key)

  alias LiveBase.Disclosure

  @doc """
  Groups all parts of the accordion.

      <.accordion id="faq">
        <:item id="faq-1" title="What is Base UI?">
          Base UI is a library of unstyled components.
        </:item>
      </.accordion>

  Opening and closing runs entirely on the client. The server is not told,
  and does not need to be: the state is which panel a reader is looking at.
  """
  attr(:id, :string,
    required: true,
    doc: "The id every item id and ARIA reference is derived from."
  )

  attr(:multiple, :boolean,
    default: false,
    doc: "Whether multiple items can be open at the same time."
  )

  attr(:disabled, :boolean,
    default: false,
    doc: "Whether the component should ignore user interaction."
  )

  attr(:orientation, :string,
    default: "vertical",
    doc:
      "Deprecated following the [APG guidance update](https://github.com/w3c/aria-practices/pull/3434) to remove roving focus. This prop no longer affects keyboard focus behavior."
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global)

  slot :item, required: true, doc: "One collapsible panel. Its content is the panel body." do
    attr(:id, :string, required: true, doc: "Unique. Every id inside the item derives from it.")
    attr(:title, :any, required: true, doc: "The trigger content.")
    attr(:open, :boolean, doc: "Whether the panel starts open.")
    attr(:disabled, :boolean, doc: "Whether the component should ignore user interaction.")
    attr(:class, :any, doc: "Appended to the item class string.")
    attr(:trigger_class, :any, doc: "Appended to the trigger class string.")
    attr(:content_class, :any, doc: "Appended to the panel class string.")
  end

  def accordion(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "accordion"}
      id={@id}
      data-orientation={@orientation}
      data-disabled={flag(@disabled)}
      class={[upstream_fact("jsx/Accordion/class/0"), (@class || "")]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <div
        :for={{item, index} <- Enum.with_index(@item)}
        data-slot="accordion-item"
        id={item.id}
        phx-mounted={Disclosure.owned_attributes(:item)}
        data-open={flag(open?(item))}
        data-disabled={flag(disabled?(item))}
        data-index={index}
        class={[upstream_fact("jsx/AccordionItem/class/0"), (item[:class] || "")]}
      >
        <h3
          id={Disclosure.header_id(item.id)}
          phx-mounted={Disclosure.owned_attributes(:header)}
          data-open={flag(open?(item))}
          data-disabled={flag(disabled?(item))}
          data-index={index}
          class={[upstream_fact("jsx/AccordionTrigger/class/0"), (item[:trigger_class] || "")]}
        >
          <button
            data-slot="accordion-trigger"
            id={Disclosure.trigger_id(item.id)}
            type="button"
            aria-expanded={to_string(open?(item))}
            aria-controls={Disclosure.panel_id(item.id)}
            phx-click={
              interactive(
                disabled?(item),
                Disclosure.toggle(item: item.id, root: @id, multiple: @multiple)
              )
            }
            phx-mounted={Disclosure.owned_attributes(:trigger)}
            data-panel-open={flag(open?(item))}
            data-disabled={flag(disabled?(item))}
            aria-disabled={to_string(disabled?(item))}
            class={[
              upstream_fact("jsx/AccordionTrigger/class/1"),
              (item[:trigger_class] || "")
            ]}
          >
            {item.title}<LiveShadcn.Icon.icon
              name="chevron-down"
              data-slot="accordion-trigger-icon"
              class={upstream_fact("jsx/AccordionTrigger/class/2")}
            /><LiveShadcn.Icon.icon
              name="chevron-up"
              data-slot="accordion-trigger-icon"
              class={upstream_fact("jsx/AccordionTrigger/class/3")}
            />
          </button>
        </h3>
        <div
          data-slot="accordion-content"
          id={Disclosure.panel_id(item.id)}
          role="region"
          aria-labelledby={Disclosure.header_id(item.id)}
          hidden={not open?(item)}
          phx-hook={Disclosure.hook()}
          phx-mounted={Disclosure.owned_attributes(:panel)}
          data-lb-height-var="--accordion-panel-height"
          data-lb-width-var="--accordion-panel-width"
          data-open={flag(open?(item))}
          data-orientation={@orientation}
          data-disabled={flag(disabled?(item))}
          data-index={index}
          data-closed={flag(not open?(item))}
          class={upstream_fact("jsx/AccordionContent/class/0")}
        >
          <div
            class={[
              upstream_fact("jsx/AccordionContent/class/1"),
              (item[:content_class] || "")
            ]}
            data-lb-style-target
            data-lb-measure
          >
            {render_slot(item)}
          </div>
        </div>
      </div>
    </div>
    """
  end

  defp open?(item), do: item[:open] == true
  defp disabled?(item), do: item[:disabled] == true

  # A disabled disclosure ignores interaction. `aria-disabled` and
  # `pointer-events-none` say so to a reader and to a mouse, but a keypress
  # on a focused trigger reaches neither, so the command itself is withheld.
  defp interactive(false, command), do: command
  defp interactive(_disabled, _command), do: nil

  # An HTML attribute with no value, or no attribute at all. Base UI marks
  # state by presence, so `data-open=""` and a missing `data-open` are the
  # two states a shadcn class string distinguishes.
  defp flag(true), do: ""
  defp flag(_state), do: nil
end