defmodule LiveShadcn.UI.Alert do
  @moduledoc """
  Alert.

  Generated by `mix ui.gen` from `registry/spec/shadcn/alert.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `alert` part."
  attr(:variant, :string, default: "default", values: ["default", "destructive"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def alert(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "alert"}
      role="alert"
      class={[
        variant_class("alertVariants", "variant", @variant),
        "cn-alert group/alert relative w-full",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `alert-title` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def alert_title(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "alert-title"}
      class={[
        "cn-alert-title [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `alert-description` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def alert_description(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "alert-description"}
      class={[
        "cn-alert-description [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `alert-action` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def alert_action(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "alert-action"}
      class={["cn-alert-action", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "alertVariants" => %{
      "variant" => %{
        "default" => "cn-alert-variant-default",
        "destructive" => "cn-alert-variant-destructive"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
