defmodule LiveShadcn.UI.AspectRatio do
  @moduledoc """
  Aspect ratio.

  Generated by `mix ui.gen` from `registry/spec/shadcn/aspect-ratio.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `aspect-ratio` part."
  attr(:ratio, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def aspect_ratio(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "aspect-ratio"}
      style={"--ratio: #{@ratio}"}
      class={["relative aspect-(--ratio)", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end
end
