defmodule LiveShadcn.UI.Attachment do
  @moduledoc """
  Attachment.

  Generated by `mix ui.gen` from `registry/spec/shadcn/attachment.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `attachment` part."
  attr(:orientation, :string, default: "horizontal", values: ["horizontal", "vertical"])
  attr(:size, :string, default: "default", values: ["default", "sm", "xs"])
  attr(:state, :string, default: "done")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "attachment"}
      data-state={@state}
      data-size={@size}
      data-orientation={@orientation}
      class={[
        "cn-attachment group/attachment relative flex max-w-full min-w-0 shrink-0 flex-wrap border bg-card text-card-foreground transition-colors has-[>a,>button]:hover:bg-muted/50 data-[state=error]:border-destructive/30 data-[state=idle]:border-dashed",
        variant_class("orientation", @orientation),
        variant_class("size", @size),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment-group` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_group(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "attachment-group"}
      class={[
        "cn-attachment-group flex min-w-0 scroll-fade-x snap-x snap-mandatory scrollbar-none overflow-x-auto overscroll-x-contain *:data-[slot=attachment]:flex-none *:data-[slot=attachment]:snap-start",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment-media` part."
  attr(:variant, :string, default: "icon", values: ["icon", "image"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_media(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "attachment-media"}
      data-variant={@variant}
      class={[
        "cn-attachment-media relative flex aspect-square shrink-0 items-center justify-center overflow-hidden group-data-[state=error]/attachment:bg-destructive/10 group-data-[state=error]/attachment:text-destructive [&_svg]:pointer-events-none",
        variant_class("variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment-content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_content(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "attachment-content"}
      class={["cn-attachment-content max-w-full min-w-0 flex-1", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment-title` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_title(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "attachment-title"}
      class={[
        "cn-attachment-title block max-w-full min-w-0 truncate group-data-[state=processing]/attachment:shimmer group-data-[state=uploading]/attachment:shimmer",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `attachment-description` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_description(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "attachment-description"}
      class={[
        "cn-attachment-description block min-w-0 truncate text-muted-foreground group-data-[state=error]/attachment:text-destructive/80 max-w-full",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `attachment-actions` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_actions(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "attachment-actions"}
      class={["cn-attachment-actions flex shrink-0 items-center", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment-action` part."
  attr(:size, :string, default: "icon-xs")
  attr(:variant, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def attachment_action(assigns) do
    ~H"""
    <LiveShadcn.UI.Button.button
      data-slot={@rest[:"data-slot"] || "attachment-action"}
      variant={@variant || "ghost"}
      size={@size}
      class={["cn-attachment-action", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </LiveShadcn.UI.Button.button>
    """
  end

  @doc "The `attachment-trigger` part."
  attr(:type, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def attachment_trigger(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "attachment-trigger"}
      class={["cn-attachment-trigger absolute inset-0 z-10 outline-none", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  # The variant table, from the `cva` call upstream writes it in.
  @variants %{
    "orientation" => %{
      "horizontal" => "cn-attachment-orientation-horizontal items-center",
      "vertical" => "cn-attachment-orientation-vertical flex-col"
    },
    "size" => %{
      "default" => "cn-attachment-size-default",
      "sm" => "cn-attachment-size-sm",
      "xs" => "cn-attachment-size-xs"
    },
    "variant" => %{
      "icon" => "cn-attachment-media-variant-icon",
      "image" =>
        "cn-attachment-media-variant-image *:[img]:aspect-square *:[img]:w-full *:[img]:object-cover"
    }
  }

  defp variant_class(group, value), do: get_in(@variants, [group, value])
end
