defmodule LiveShadcn.UI.Badge do
  @moduledoc """
  Badge.

  Generated by `mix ui.gen` from `registry/spec/badge.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `badge` part."
  attr(:variant, :string,
    default: "default",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def badge(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "badge"}
      class={[
        "cn-badge group/badge inline-flex w-fit shrink-0 items-center justify-center overflow-hidden whitespace-nowrap focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none",
        variant_class("variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  # The variant table, from the `cva` call upstream writes it in.
  @variants %{
    "variant" => %{
      "default" => "cn-badge-variant-default",
      "destructive" => "cn-badge-variant-destructive",
      "ghost" => "cn-badge-variant-ghost",
      "link" => "cn-badge-variant-link",
      "outline" => "cn-badge-variant-outline",
      "secondary" => "cn-badge-variant-secondary"
    }
  }

  defp variant_class(group, value), do: get_in(@variants, [group, value])
end
