defmodule LiveShadcn.UI.Breadcrumb do
  @moduledoc """
  Breadcrumb.

  Generated by `mix ui.gen` from `registry/spec/breadcrumb.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `breadcrumb` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def breadcrumb(assigns) do
    ~H"""
    <nav
      data-slot={@rest[:"data-slot"] || "breadcrumb"}
      aria-label="breadcrumb"
      class={["cn-breadcrumb", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </nav>
    """
  end

  @doc "The `breadcrumb-list` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "start", "reversed"])
  slot(:inner_block)

  def breadcrumb_list(assigns) do
    ~H"""
    <ol
      data-slot={@rest[:"data-slot"] || "breadcrumb-list"}
      class={["cn-breadcrumb-list flex flex-wrap items-center wrap-break-word", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </ol>
    """
  end

  @doc "The `breadcrumb-item` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def breadcrumb_item(assigns) do
    ~H"""
    <li
      data-slot={@rest[:"data-slot"] || "breadcrumb-item"}
      class={["cn-breadcrumb-item inline-flex items-center", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </li>
    """
  end

  @doc "The `breadcrumb-link` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "href", "target", "rel", "download", "hreflang"])
  slot(:inner_block)

  def breadcrumb_link(assigns) do
    ~H"""
    <a
      data-slot={@rest[:"data-slot"] || "breadcrumb-link"}
      class={["cn-breadcrumb-link", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </a>
    """
  end

  @doc "The `breadcrumb-page` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def breadcrumb_page(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "breadcrumb-page"}
      role="link"
      aria-disabled="true"
      aria-current="page"
      class={["cn-breadcrumb-page", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `breadcrumb-separator` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def breadcrumb_separator(assigns) do
    ~H"""
    <li
      data-slot={@rest[:"data-slot"] || "breadcrumb-separator"}
      role="presentation"
      aria-hidden="true"
      class={["cn-breadcrumb-separator", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </li>
    """
  end

  @doc "The `breadcrumb-ellipsis` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def breadcrumb_ellipsis(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "breadcrumb-ellipsis"}
      role="presentation"
      aria-hidden="true"
      class={["cn-breadcrumb-ellipsis flex items-center justify-center", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <LiveShadcn.Icon.icon name="more-horizontal" />
      <span class="sr-only">
        More
      </span>
      {render_slot(@inner_block)}
    </span>
    """
  end
end
