defmodule LiveShadcn.UI.Bubble do
  @moduledoc """
  Bubble.

  Generated by `mix ui.gen` from `registry/spec/shadcn/bubble.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `bubble-group` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def bubble_group(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "bubble-group"}
      class={["cn-bubble-group flex min-w-0 flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `bubble` part."
  attr(:align, :string, default: "start")

  attr(:variant, :string,
    default: "default",
    values: ["default", "destructive", "ghost", "muted", "outline", "secondary", "tinted"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def bubble(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "bubble"}
      data-variant={@variant}
      data-align={@align}
      class={[
        "cn-bubble group/bubble relative flex w-fit min-w-0 flex-col",
        variant_class("variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `bubble-content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def bubble_content(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "bubble-content"}
      class={[
        "cn-bubble-content w-fit max-w-full min-w-0 overflow-hidden wrap-break-word [button]:text-left [button,a]:transition-colors",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `bubble-reactions` part."
  attr(:align, :string, default: "end", values: ["end", "start"])
  attr(:side, :string, default: "bottom", values: ["bottom", "top"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def bubble_reactions(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "bubble-reactions"}
      data-align={@align}
      data-side={@side}
      class={[
        "cn-bubble-reactions absolute z-10 flex w-fit items-center justify-center",
        variant_class("align", @align),
        variant_class("side", @side),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  # The variant table, from the `cva` call upstream writes it in.
  @variants %{
    "align" => %{
      "end" => "cn-bubble-reactions-align-end",
      "start" => "cn-bubble-reactions-align-start"
    },
    "side" => %{
      "bottom" => "cn-bubble-reactions-side-bottom",
      "top" => "cn-bubble-reactions-side-top"
    },
    "variant" => %{
      "default" => "cn-bubble-variant-default",
      "destructive" => "cn-bubble-variant-destructive",
      "ghost" => "cn-bubble-variant-ghost",
      "muted" => "cn-bubble-variant-muted",
      "outline" => "cn-bubble-variant-outline",
      "secondary" => "cn-bubble-variant-secondary",
      "tinted" => "cn-bubble-variant-tinted"
    }
  }

  defp variant_class(group, value), do: get_in(@variants, [group, value])
end
