defmodule LiveShadcn.UI.Button do
  @moduledoc """
  Button. A button component that can be used to trigger actions.

  Generated by `mix ui.gen` from `registry/spec/shadcn/button.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `button` part."
  attr(:size, :string,
    default: "default",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:variant, :string,
    default: "default",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def button(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "button"}
      class={[
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
        variant_class("buttonVariants", "size", @size),
        variant_class("buttonVariants", "variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "size" => %{
        "default" => "cn-button-size-default",
        "icon" => "cn-button-size-icon",
        "icon-lg" => "cn-button-size-icon-lg",
        "icon-sm" => "cn-button-size-icon-sm",
        "icon-xs" => "cn-button-size-icon-xs",
        "lg" => "cn-button-size-lg",
        "sm" => "cn-button-size-sm",
        "xs" => "cn-button-size-xs"
      },
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
