defmodule LiveShadcn.UI.Checkbox do
  @moduledoc """
  Checkbox. Represents the checkbox itself.

  Generated by `mix ui.gen` from `registry/spec/shadcn/checkbox.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  # live-shadcn: upstream facts start
  @upstream_facts %{
    "jsx/Checkbox/class/0" => "cn-checkbox peer relative shrink-0 outline-none after:absolute after:-inset-x-3 after:-inset-y-2 disabled:cursor-not-allowed disabled:opacity-50",
    "jsx/Checkbox/class/1" => "cn-checkbox-indicator grid place-content-center text-current transition-none"
  }
  # live-shadcn: upstream facts end
  Module.get_attribute(__MODULE__, :upstream_facts)

  defp upstream_fact(key), do: Map.fetch!(@upstream_facts, key)

  alias LiveBase.FormControl

  @doc """
  Represents the checkbox itself.

      <.checkbox field={@form[:subscribe]} />

  The control a reader sees and the input a form submits are two elements,
  as Base UI documents. Flipping one flips the other, on the client, so a
  click costs no round trip and `phx-change` still fires.

  It needs an accessible name, and a `<label for>` cannot give it one: a
  label names a labelable element, and this is not one. Name it directly:

      <.label id="subscribe-label">Send me the pull requests</.label>
      <.checkbox field={@form[:subscribe]} aria-labelledby="subscribe-label" />
  """
  attr(:field, Phoenix.HTML.FormField,
    default: nil,
    doc: "A form field. Fills in id, name, value and errors."
  )

  attr(:id, :string, default: nil)
  attr(:name, :string, default: nil)
  attr(:value, :string, default: "true", doc: "What the form submits when the control is on.")
  attr(:checked, :boolean, default: nil)
  attr(:errors, :list, default: [])
  attr(:disabled, :boolean, default: false)
  attr(:readonly, :boolean, default: false)
  attr(:required, :boolean, default: false)
  attr(:indeterminate, :boolean, default: false)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def checkbox(assigns) do
    assigns = FormControl.from_checkable(assigns)

    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "checkbox"}
      role="checkbox"
      tabindex="0"
      id={@id}
      aria-checked={to_string(@checked)}
      aria-disabled={to_string(@disabled)}
      phx-click={if(@disabled or @readonly, do: nil, else: FormControl.toggle(control: @id))}
      phx-mounted={FormControl.owned_attributes()}
      phx-keydown={if(@disabled or @readonly, do: nil, else: FormControl.toggle(control: @id))}
      phx-key=" "
      data-checked={flag(@checked)}
      data-unchecked={flag(not @checked)}
      data-disabled={flag(@disabled)}
      data-readonly={flag(@readonly)}
      data-required={flag(@required)}
      data-valid={flag(@errors == [])}
      data-invalid={flag(@errors != [])}
      data-filled={flag(@checked)}
      data-indeterminate={flag(@indeterminate)}
      class={[
        upstream_fact("jsx/Checkbox/class/0"),
        (@class || "")
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <span
        hidden={not @checked}
        data-slot="checkbox-indicator"
        class={upstream_fact("jsx/Checkbox/class/1")}
      >
        <LiveShadcn.Icon.icon name="check" />
      </span>
      {render_slot(@inner_block)}
    </span>
    <input
      type="checkbox"
      id={FormControl.input_id(@id)}
      name={@name}
      value={@value}
      checked={@checked}
      disabled={@disabled}
      required={@required}
      tabindex="-1"
      aria-hidden="true"
      class="sr-only"
    />
    """
  end

  defp flag(true), do: ""
  defp flag(_state), do: nil
end