defmodule LiveShadcn.UI.Command do
  @moduledoc """
  Command.

  Upstream exports 1 more parts, and every one of them is a
  thin wrapper around a part of `<.dialog>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/shadcn/command.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `command` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def command(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "command"}
      class={["cn-command flex size-full flex-col overflow-hidden", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `command-input-wrapper` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: [
      "data-slot",
      "type",
      "name",
      "value",
      "placeholder",
      "checked",
      "min",
      "max",
      "step",
      "minlength",
      "maxlength",
      "pattern",
      "readonly",
      "multiple"
    ]
  )

  slot(:inner_block)

  def command_input(assigns) do
    ~H"""
    <div data-slot="command-input-wrapper" class="cn-command-input-wrapper">
      <LiveShadcn.UI.InputGroup.input_group class="cn-command-input-group">
        <input
          data-slot={@rest[:"data-slot"] || "command-input"}
          class={[
            "cn-command-input outline-hidden disabled:cursor-not-allowed disabled:opacity-50",
            @class
          ]}
          {Map.drop(@rest, [:"data-slot"])}
        />
        <LiveShadcn.UI.InputGroup.input_group_addon>
          <LiveShadcn.Icon.icon name="search" class="cn-command-input-icon" />
        </LiveShadcn.UI.InputGroup.input_group_addon>
      </LiveShadcn.UI.InputGroup.input_group>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `command-list` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def command_list(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "command-list"}
      class={["cn-command-list overflow-x-hidden overflow-y-auto", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `command-empty` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def command_empty(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "command-empty"}
      class={["cn-command-empty", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `command-group` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def command_group(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "command-group"}
      class={["cn-command-group", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `command-item` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def command_item(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "command-item"}
      class={[
        "cn-command-item group/command-item data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
      <LiveShadcn.Icon.icon
        name="check"
        class="cn-command-item-indicator ml-auto opacity-0 group-has-data-[slot=command-shortcut]/command-item:hidden group-data-[checked=true]/command-item:opacity-100"
      />
    </div>
    """
  end

  @doc "The `command-shortcut` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def command_shortcut(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "command-shortcut"}
      class={["cn-command-shortcut", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `command-separator` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def command_separator(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "command-separator"}
      class={["cn-command-separator", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end
end
