defmodule LiveShadcn.UI.Empty do
  @moduledoc """
  Empty.

  Generated by `mix ui.gen` from `registry/spec/shadcn/empty.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `empty` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def empty(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "empty"}
      class={[
        "cn-empty flex w-full min-w-0 flex-1 flex-col items-center justify-center text-center text-balance",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `empty-header` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def empty_header(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "empty-header"}
      class={["cn-empty-header flex max-w-sm flex-col items-center", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `empty-title` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def empty_title(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "empty-title"}
      class={["cn-empty-title cn-font-heading", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `empty-description` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def empty_description(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "empty-description"}
      class={[
        "cn-empty-description text-muted-foreground [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `empty-content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def empty_content(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "empty-content"}
      class={[
        "cn-empty-content flex w-full max-w-sm min-w-0 flex-col items-center text-balance",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `empty-icon` part."
  attr(:variant, :string, default: "default", values: ["default", "icon"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def empty_media(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "empty-icon"}
      data-variant={@variant}
      class={[
        variant_class("emptyMediaVariants", "variant", @variant),
        "cn-empty-media flex shrink-0 items-center justify-center [&_svg]:pointer-events-none [&_svg]:shrink-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "emptyMediaVariants" => %{
      "variant" => %{
        "default" => "cn-empty-media-default",
        "icon" => "cn-empty-media-icon"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
