defmodule LiveShadcn.UI.Field do
  @moduledoc """
  Field. Groups all parts of the field.

  Generated by `mix ui.gen` from `registry/spec/shadcn/field.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `field` part."
  attr(:orientation, :string,
    default: "vertical",
    values: ["horizontal", "responsive", "vertical"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def field(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "field"}
      role="group"
      data-orientation={@orientation}
      class={[
        variant_class("fieldVariants", "orientation", @orientation),
        "cn-field group/field flex w-full",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `field-label` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "for"])
  slot(:inner_block)

  def field_label(assigns) do
    ~H"""
    <LiveShadcn.UI.Label.label
      data-slot={@rest[:"data-slot"] || "field-label"}
      class={[
        "cn-field-label group/field-label peer/field-label flex w-fit has-[>[data-slot=field]]:w-full has-[>[data-slot=field]]:flex-col",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </LiveShadcn.UI.Label.label>
    """
  end

  @doc "The `field-description` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def field_description(assigns) do
    ~H"""
    <p
      data-slot={@rest[:"data-slot"] || "field-description"}
      class={[
        "cn-field-description leading-normal font-normal group-has-data-horizontal/field:text-balance last:mt-0 nth-last-2:-mt-1 [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </p>
    """
  end

  @doc "The `field-error` part."
  attr(:content, :string, default: nil)
  attr(:errors, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def field_error(assigns) do
    ~H"""
    <div
      :if={@content}
      data-slot={@rest[:"data-slot"] || "field-error"}
      role="alert"
      class={["cn-field-error font-normal", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {@content}{render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `field-group` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def field_group(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "field-group"}
      class={["cn-field-group group/field-group @container/field-group flex w-full flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `field-legend` part."
  attr(:variant, :string, default: "legend", values: ["legend", "label"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def field_legend(assigns) do
    ~H"""
    <legend
      data-slot={@rest[:"data-slot"] || "field-legend"}
      data-variant={@variant}
      class={["cn-field-legend", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </legend>
    """
  end

  @doc "The `field-separator` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def field_separator(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "field-separator"}
      data-content={@children not in [nil, false, ""]}
      class={["cn-field-separator relative", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <LiveShadcn.UI.Separator.separator class="absolute inset-0 top-1/2" />
      <span
        :if={@children}
        data-slot="field-separator-content"
        class="cn-field-separator-content relative mx-auto block w-fit bg-background"
      >
        {render_slot(@inner_block)}
      </span>
    </div>
    """
  end

  @doc "The `field-set` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def field_set(assigns) do
    ~H"""
    <fieldset
      data-slot={@rest[:"data-slot"] || "field-set"}
      class={["cn-field-set flex flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </fieldset>
    """
  end

  @doc "The `field-content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def field_content(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "field-content"}
      class={["cn-field-content group/field-content flex flex-1 flex-col leading-snug", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `field-label` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def field_title(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "field-label"}
      class={["cn-field-title flex w-fit items-center", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "fieldVariants" => %{
      "orientation" => %{
        "horizontal" =>
          "cn-field-orientation-horizontal flex-row items-center has-[>[data-slot=field-content]]:items-start *:data-[slot=field-label]:flex-auto has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
        "responsive" =>
          "cn-field-orientation-responsive flex-col *:w-full @md/field-group:flex-row @md/field-group:items-center @md/field-group:*:w-auto @md/field-group:has-[>[data-slot=field-content]]:items-start @md/field-group:*:data-[slot=field-label]:flex-auto [&>.sr-only]:w-auto @md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
        "vertical" => "cn-field-orientation-vertical flex-col *:w-full [&>.sr-only]:w-auto"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
