defmodule LiveShadcn.UI.InputOtp do
  @moduledoc """
  Input otp.

  Generated by `mix ui.gen` from `registry/spec/shadcn/input-otp.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.FormControl

  @doc """
  The `input-otp` part.

      <.input_otp field={@form[:email]} />

  A `:field` fills in the id, the name, the value, and the errors. Errors
  show only once the form has been used: an untouched form is not a form
  with mistakes in it.
  """
  attr(:field, Phoenix.HTML.FormField,
    default: nil,
    doc: "A form field. Fills in id, name, value and errors."
  )

  attr(:id, :string, default: nil)
  attr(:name, :string, default: nil)
  attr(:value, :any, default: nil, doc: "The field's value.")
  attr(:errors, :list, default: [])
  attr(:disabled, :boolean, default: false)
  attr(:readonly, :boolean, default: false)
  attr(:required, :boolean, default: false)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: [
      "data-slot",
      "type",
      "name",
      "value",
      "placeholder",
      "checked",
      "min",
      "max",
      "step",
      "pattern",
      "readonly",
      "multiple"
    ]
  )

  def input_otp(assigns) do
    assigns = FormControl.from_field(assigns)

    ~H"""
    <input
      data-slot={@rest[:"data-slot"] || "input-otp"}
      id={@id}
      name={@name}
      value={@value}
      disabled={@disabled}
      readonly={@readonly}
      required={@required}
      phx-mounted={FormControl.owned_attributes()}
      spellcheck={false}
      class={["cn-input-otp-input disabled:cursor-not-allowed", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    />
    """
  end

  @doc "The `input-otp-group` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def input_otp_group(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "input-otp-group"}
      class={["cn-input-otp-group flex items-center", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `input-otp-slot` part."
  attr(:char, :string, default: nil)
  attr(:has_fake_caret, :string, default: nil)
  attr(:is_active, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def input_otp_slot(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "input-otp-slot"}
      data-active={@is_active}
      class={[
        "cn-input-otp-slot relative flex items-center justify-center data-[active=true]:z-10",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {@char}
      <div
        :if={@has_fake_caret}
        class="cn-input-otp-caret pointer-events-none absolute inset-0 flex items-center justify-center"
      >
        <div class="cn-input-otp-caret-line" />
      </div>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `input-otp-separator` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def input_otp_separator(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "input-otp-separator"}
      role="separator"
      class="cn-input-otp-separator flex items-center"
      {Map.drop(@rest, [:"data-slot"])}
    >
      <LiveShadcn.Icon.icon name="minus" />
      {render_slot(@inner_block)}
    </div>
    """
  end
end
