defmodule LiveShadcn.UI.Input do
  @moduledoc """
  Input. A native input element that automatically works with [Field](https://base-ui.com/react/components/field).

  Generated by `mix ui.gen` from `registry/spec/shadcn/input.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.FormControl

  @doc """
  A native input element that automatically works with [Field](https://base-ui.com/react/components/field).

      <.input field={@form[:email]} />

  A `:field` fills in the id, the name, the value, and the errors. Errors
  show only once the form has been used: an untouched form is not a form
  with mistakes in it.
  """
  attr(:field, Phoenix.HTML.FormField,
    default: nil,
    doc: "A form field. Fills in id, name, value and errors."
  )

  attr(:id, :string, default: nil)
  attr(:name, :string, default: nil)
  attr(:value, :any, default: nil, doc: "The field's value.")
  attr(:errors, :list, default: [])
  attr(:disabled, :boolean, default: false)
  attr(:readonly, :boolean, default: false)
  attr(:required, :boolean, default: false)
  attr(:type, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: [
      "data-slot",
      "type",
      "name",
      "value",
      "placeholder",
      "checked",
      "min",
      "max",
      "step",
      "minlength",
      "maxlength",
      "pattern",
      "readonly",
      "multiple",
      "autocomplete",
      "disabled",
      "required"
    ]
  )

  def input(assigns) do
    assigns = FormControl.from_field(assigns)

    ~H"""
    <input
      data-slot={@rest[:"data-slot"] || "input"}
      id={@id}
      name={@name}
      value={@value}
      disabled={@disabled}
      readonly={@readonly}
      required={@required}
      phx-mounted={FormControl.owned_attributes()}
      data-disabled={flag(@disabled)}
      data-valid={flag(@errors == [])}
      data-invalid={flag(@errors != [])}
      data-filled={flag(@value not in [nil, ""])}
      type={@type}
      class={[
        "cn-input w-full min-w-0 outline-none file:inline-flex file:border-0 file:bg-transparent file:text-foreground placeholder:text-muted-foreground disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    />
    """
  end

  defp flag(true), do: ""
  defp flag(_state), do: nil
end
