defmodule LiveShadcn.UI.Marker do
  @moduledoc """
  Marker.

  Generated by `mix ui.gen` from `registry/spec/marker.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `marker` part."
  attr(:variant, :string, default: "default", values: ["border", "default", "separator"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def marker(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "marker"}
      class={[
        "cn-marker group/marker relative flex w-full items-center",
        variant_class("variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `marker-icon` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def marker_icon(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "marker-icon"}
      aria-hidden="true"
      class={["cn-marker-icon shrink-0", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `marker-content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def marker_content(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "marker-content"}
      class={["cn-marker-content min-w-0 wrap-break-word", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  # The variant table, from the `cva` call upstream writes it in.
  @variants %{
    "variant" => %{
      "border" => "cn-marker-variant-border",
      "default" => "cn-marker-variant-default",
      "separator" => "cn-marker-variant-separator"
    }
  }

  defp variant_class(group, value), do: get_in(@variants, [group, value])
end
