defmodule LiveShadcn.UI.Menubar do
  @moduledoc """
  Menubar. The container for menus.

  Upstream exports 13 more parts, and every one of them is a
  thin wrapper around a part of `<.dropdown_menu>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/shadcn/menubar.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `menubar` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def menubar(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "menubar"}
      class={["cn-menubar flex items-center", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `menubar-checkbox-item` part."
  attr(:checked, :string, default: nil)
  attr(:inset, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def menubar_checkbox_item(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "menubar-checkbox-item"}
      data-inset={@inset}
      checked={@checked}
      class={[
        "cn-menubar-checkbox-item relative flex cursor-default items-center outline-hidden select-none data-disabled:pointer-events-none data-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <span class="cn-menubar-checkbox-item-indicator pointer-events-none absolute flex items-center justify-center">
        <span>
          <LiveShadcn.Icon.icon name="check" />
        </span>
      </span>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `menubar-radio-item` part."
  attr(:inset, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def menubar_radio_item(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "menubar-radio-item"}
      data-inset={@inset}
      class={[
        "cn-menubar-radio-item relative flex cursor-default items-center outline-hidden select-none data-disabled:pointer-events-none [&_svg]:pointer-events-none [&_svg]:shrink-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <span class="cn-menubar-radio-item-indicator pointer-events-none absolute flex items-center justify-center">
        <span>
          <LiveShadcn.Icon.icon name="check" />
        </span>
      </span>
      {render_slot(@inner_block)}
    </div>
    """
  end
end
