defmodule LiveShadcn.UI.Message do
  @moduledoc """
  Message.

  Generated by `mix ui.gen` from `registry/spec/shadcn/message.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `message-group` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message_group(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "message-group"}
      class={["cn-message-group flex min-w-0 flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `message` part."
  attr(:align, :string, default: "start")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "message"}
      data-align={@align}
      class={[
        "cn-message group/message relative flex w-full min-w-0 data-[align=end]:flex-row-reverse",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `message-avatar` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message_avatar(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "message-avatar"}
      class={[
        "cn-message-avatar flex w-fit shrink-0 items-center justify-center self-end overflow-hidden rounded-full bg-muted",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `message-content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message_content(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "message-content"}
      class={["cn-message-content flex w-full min-w-0 flex-col wrap-break-word", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `message-footer` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message_footer(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "message-footer"}
      class={[
        "cn-message-footer flex max-w-full min-w-0 items-center group-data-[align=end]/message:justify-end",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `message-header` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message_header(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "message-header"}
      class={["cn-message-header flex max-w-full min-w-0 items-center", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end
end
