defmodule LiveShadcn.UI.MessageScroller do
  @moduledoc """
  Message scroller.

  Generated by `mix ui.gen` from `registry/spec/shadcn/message-scroller.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `message_scroller_provider` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message_scroller_provider(assigns) do
    ~H"""
    {render_slot(@inner_block)}
    """
  end

  @doc "The `message-scroller` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message_scroller(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "message-scroller"}
      class={[
        "cn-message-scroller group/message-scroller relative flex size-full min-h-0 flex-col overflow-hidden",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `message-scroller-viewport` part."

  attr(:id, :string, required: true, doc: "The hook needs one to be found by.")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message_scroller_viewport(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "message-scroller-viewport"}
      id={@id}
      data-lb-scroller
      data-lb-stick-to-bottom
      tabindex="0"
      phx-hook={LiveBase.Scroller.hook()}
      phx-mounted={LiveBase.Scroller.owned_attributes()}
      class={[
        "cn-message-scroller-viewport size-full min-h-0 min-w-0 scroll-fade-b scrollbar-thin scrollbar-gutter-stable overflow-y-auto overscroll-contain contain-content data-autoscrolling:scrollbar-thumb-transparent data-autoscrolling:scrollbar-track-transparent",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `message-scroller-content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message_scroller_content(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "message-scroller-content"}
      class={["cn-message-scroller-content flex h-max min-h-full flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `message-scroller-item` part."
  attr(:scroll_anchor, :boolean, default: false)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def message_scroller_item(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "message-scroller-item"}
      class={[
        "cn-message-scroller-item min-w-0 shrink-0 [contain-intrinsic-size:auto_10rem] [content-visibility:auto]",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `message-scroller-button` part."
  attr(:direction, :string, default: "end")
  attr(:size, :string, default: "icon-sm")
  attr(:variant, :string, default: "secondary")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction", "disabled"])
  slot(:inner_block)

  def message_scroller_button(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "message-scroller-button"}
      data-direction={@direction}
      data-variant={@variant}
      data-size={@size}
      class={[
        "cn-message-scroller-button absolute inset-s-1/2 -translate-x-1/2 border-border bg-background text-foreground transition-[translate,scale,opacity] duration-200 hover:bg-muted hover:text-foreground data-[active=false]:pointer-events-none data-[active=false]:scale-95 data-[active=false]:opacity-0 data-[active=false]:duration-400 data-[active=false]:ease-[cubic-bezier(0.7,0,0.84,0)] data-[active=true]:translate-y-0 data-[active=true]:scale-100 data-[active=true]:opacity-100 data-[active=true]:ease-[cubic-bezier(0.23,1,0.32,1)] data-[direction=end]:bottom-4 data-[direction=end]:data-[active=false]:translate-y-full data-[direction=start]:top-4 data-[direction=start]:data-[active=false]:-translate-y-full rtl:translate-x-1/2 data-[direction=start]:[&_svg]:rotate-180",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon name="arrow-down" /><span class="sr-only">{if(@direction == "end",
          do: "Scroll to end",
          else: "Scroll to start"
        )}</span>
      <% end %>
      {render_slot(@inner_block)}
    </button>
    """
  end
end
