defmodule LiveShadcn.UI.NativeSelect do
  @moduledoc """
  Native select.

  Generated by `mix ui.gen` from `registry/spec/shadcn/native-select.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `native-select-wrapper` part."
  attr(:size, :string, default: "default", values: ["sm", "default"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "name", "multiple", "size", "disabled", "required"])
  slot(:inner_block)

  def native_select(assigns) do
    ~H"""
    <div
      data-slot="native-select-wrapper"
      data-size={@size}
      class={[
        "cn-native-select-wrapper group/native-select relative w-fit has-[select:disabled]:opacity-50",
        @class
      ]}
    >
      <select
        data-slot={@rest[:"data-slot"] || "native-select"}
        data-size={@size}
        class="cn-native-select outline-none disabled:pointer-events-none disabled:cursor-not-allowed"
        {Map.drop(@rest, [:"data-slot"])}
      >
        {render_slot(@inner_block)}
      </select>
      <LiveShadcn.Icon.icon
        name="chevron-down"
        data-slot="native-select-icon"
        class="cn-native-select-icon pointer-events-none absolute select-none"
      />
    </div>
    """
  end

  @doc "The `native-select-optgroup` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def native_select_opt_group(assigns) do
    ~H"""
    <optgroup
      data-slot={@rest[:"data-slot"] || "native-select-optgroup"}
      class={["bg-[Canvas] text-[CanvasText]", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </optgroup>
    """
  end

  @doc "The `native-select-option` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "value", "selected"])
  slot(:inner_block)

  def native_select_option(assigns) do
    ~H"""
    <option
      data-slot={@rest[:"data-slot"] || "native-select-option"}
      class={["bg-[Canvas] text-[CanvasText]", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </option>
    """
  end
end
