defmodule LiveShadcn.UI.NavigationMenu do
  @moduledoc """
  Navigation menu. Groups navigation links and their content.

  Generated by `mix ui.gen` from `registry/spec/shadcn/navigation-menu.json`.
  Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.Popover

  attr(:id, :string, required: true, doc: "Every id inside the menu derives from it.")
  attr(:open, :boolean, default: false, doc: "Whether the content starts open.")
  attr(:disabled, :boolean, default: false, doc: "Whether the trigger refuses interaction.")
  attr(:side, :string, default: "bottom", values: ["top", "right", "bottom", "left"])
  attr(:align, :string, default: "start", values: ["start", "center", "end"])
  attr(:offset, :integer, default: 8)
  attr(:class, :any, default: nil, doc: "Appended to the root class string.")
  attr(:content_class, :any, default: nil)
  attr(:item_class, :any, default: nil)
  attr(:list_class, :any, default: nil)
  attr(:positioner_class, :any, default: nil)
  attr(:trigger_class, :any, default: nil)
  attr(:rest, :global)

  slot(:trigger, required: true, doc: "What opens the navigation content.")
  slot(:inner_block, required: true, doc: "The navigation content.")

  def navigation_menu(assigns) do
    ~H"""
    <nav
      id={@id}
      data-slot="navigation-menu"
      class={[
        "cn-navigation-menu group/navigation-menu relative flex max-w-max flex-1 items-center justify-center",
        @class
      ]}
      phx-window-keydown={Popover.close(@id)}
      phx-key="Escape"
      phx-click-away={Popover.dismiss(@id)}
      {@rest}
    >
      <ul
        data-slot="navigation-menu-list"
        class={[
          "cn-navigation-menu-list group flex flex-1 list-none items-center justify-center",
          @list_class
        ]}
      >
        <li data-slot="navigation-menu-item" class={["cn-navigation-menu-item relative", @item_class]}>
          <button
            id={Popover.trigger_id(@id)}
            type="button"
            data-slot="navigation-menu-trigger"
            aria-haspopup="menu"
            aria-expanded={to_string(@open)}
            aria-controls={Popover.popup_id(@id)}
            phx-click={if(not @disabled, do: Popover.toggle(@id))}
            phx-mounted={Popover.owned_attributes(:trigger)}
            data-open={flag(@open)}
            data-popup-open={flag(@open)}
            data-pressed={flag(@open)}
            data-disabled={flag(@disabled)}
            class={[
              "cn-navigation-menu-trigger group/navigation-menu-trigger inline-flex h-9 w-max items-center justify-center outline-none disabled:pointer-events-none group",
              @trigger_class
            ]}
          >
            {render_slot(@trigger)}
            <LiveShadcn.Icon.icon name="chevron-down" class="cn-navigation-menu-trigger-icon" />
          </button>
        </li>
      </ul>
      <div class="contents">
        <div
          id={Popover.positioner_id(@id)}
          hidden={not @open}
          phx-hook={Popover.hook()}
          data-lb-anchor={Popover.trigger_id(@id)}
          data-lb-side={@side}
          data-lb-align={@align}
          data-lb-offset={to_string(@offset)}
          data-lb-autofocus
          phx-mounted={Popover.owned_attributes(:positioner)}
          data-open={flag(@open)}
          data-closed={flag(not @open)}
          class={[
            "cn-navigation-menu-positioner isolate z-50 h-(--positioner-height) w-(--positioner-width) max-w-(--available-width) transition-[top,left,right,bottom] duration-[0.35s] data-instant:transition-none",
            @positioner_class
          ]}
          data-lb-measure
        >
          <div
            id={Popover.popup_id(@id)}
            hidden={not @open}
            data-lb-popup
            phx-mounted={Popover.owned_attributes(:popup)}
            data-open={flag(@open)}
            data-closed={flag(not @open)}
            class="cn-navigation-menu-popup data-[ending-style]:easing-[ease] xs:w-(--popup-width) relative h-(--popup-height) w-(--popup-width) origin-(--transform-origin) transition-[opacity,transform,width,height,scale,translate] duration-[0.35s] ease-[cubic-bezier(0.22,1,0.36,1)]"
            data-lb-style-target
            data-lb-measure
          >
            <div data-slot="navigation-menu-viewport" class="relative size-full overflow-hidden">
              <div
                data-slot="navigation-menu-content"
                data-open={flag(@open)}
                data-closed={flag(not @open)}
                class={[
                  "cn-navigation-menu-content data-ending-style:data-activation-direction=left:translate-x-[50%] data-ending-style:data-activation-direction=right:translate-x-[-50%] data-starting-style:data-activation-direction=left:translate-x-[-50%] data-starting-style:data-activation-direction=right:translate-x-[50%] h-full w-auto transition-[opacity,transform,translate] duration-[0.35s] data-ending-style:opacity-0 data-starting-style:opacity-0 **:data-[slot=navigation-menu-link]:focus:ring-0 **:data-[slot=navigation-menu-link]:focus:outline-none",
                  @content_class
                ]}
              >
                {render_slot(@inner_block)}
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    """
  end

  defp flag(true), do: ""
  defp flag(_state), do: nil
end
