defmodule LiveShadcn.UI.Questionnaire do
  @moduledoc """
  Questionnaire.

  Generated by `mix ui.gen` from `registry/spec/shadcn/questionnaire.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `questionnaire` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: ["data-slot", "action", "method", "enctype", "novalidate", "target"]
  )

  slot(:inner_block)

  def questionnaire(assigns) do
    ~H"""
    <form
      data-slot={@rest[:"data-slot"] || "questionnaire"}
      class={["cn-questionnaire flex w-full min-w-0 flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </form>
    """
  end

  @doc "The `questionnaire-actions` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def questionnaire_actions(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "questionnaire-actions"}
      class={[
        "cn-questionnaire-actions grid min-h-11 w-full grid-cols-[minmax(0,1fr)_auto_auto] items-center",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `questionnaire-choice` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "for"])
  slot(:inner_block)

  def questionnaire_choice(assigns) do
    ~H"""
    <label
      data-slot={@rest[:"data-slot"] || "questionnaire-choice"}
      class={[
        "cn-questionnaire-choice group/questionnaire-choice relative flex min-h-11 cursor-pointer items-start text-start transition-colors outline-none select-none data-disabled:pointer-events-none data-disabled:cursor-not-allowed data-disabled:opacity-50",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <input
        data-slot="questionnaire-choice-input"
        type="radio"
        class="cn-questionnaire-choice-input absolute inset-0 z-10 size-full cursor-pointer opacity-0"
      />
      <span
        data-slot="questionnaire-choice-indicator"
        aria-hidden="true"
        class="cn-questionnaire-choice-indicator pointer-events-none relative flex shrink-0 items-center justify-center border group-data-[type=radio]/questionnaire-choice:rounded-full"
      >
        <span
          data-slot="questionnaire-choice-indicator-dot"
          class="cn-questionnaire-choice-indicator-dot hidden rounded-full group-data-[type=checkbox]/questionnaire-choice:hidden group-data-checked/questionnaire-choice:block"
        />
        <LiveShadcn.Icon.icon
          name="check"
          data-slot="questionnaire-choice-indicator-check"
          class="cn-questionnaire-choice-indicator-check hidden group-data-[type=radio]/questionnaire-choice:hidden group-data-checked/questionnaire-choice:block"
        />
      </span>
      <span
        data-slot="questionnaire-choice-label"
        class="cn-questionnaire-choice-label cn-questionnaire-choice-content flex min-w-0 flex-1 flex-col leading-snug"
      >
        {render_slot(@inner_block)}
      </span>
    </label>
    """
  end

  @doc "The `questionnaire-choice-description` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def questionnaire_choice_description(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "questionnaire-choice-description"}
      class={["cn-questionnaire-choice-description", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `questionnaire-choices` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def questionnaire_choices(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "questionnaire-choices"}
      class={["cn-questionnaire-choices group/questionnaire-choices grid min-w-0", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `questionnaire-description` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def questionnaire_description(assigns) do
    ~H"""
    <p
      data-slot={@rest[:"data-slot"] || "questionnaire-description"}
      class={["cn-questionnaire-description text-pretty text-muted-foreground", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </p>
    """
  end

  @doc "The `questionnaire-error` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def questionnaire_error(assigns) do
    ~H"""
    <p
      data-slot={@rest[:"data-slot"] || "questionnaire-error"}
      class={["cn-questionnaire-error text-destructive", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </p>
    """
  end

  @doc "The `questionnaire-input-wrapper` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: [
      "data-slot",
      "type",
      "name",
      "value",
      "placeholder",
      "checked",
      "min",
      "max",
      "step",
      "pattern",
      "readonly",
      "multiple"
    ]
  )

  slot(:inner_block)

  def questionnaire_input(assigns) do
    ~H"""
    <div
      data-slot="questionnaire-input-wrapper"
      class="cn-questionnaire-input-wrapper group/questionnaire-input relative min-w-0"
    >
      <input
        data-slot={@rest[:"data-slot"] || "questionnaire-input"}
        class={[
          "cn-questionnaire-input min-h-11 w-full min-w-0 transition-[color,box-shadow,background-color] outline-none disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 sm:min-h-0 selection:bg-primary selection:text-primary-foreground placeholder:text-muted-foreground",
          @class
        ]}
        {Map.drop(@rest, [:"data-slot"])}
      />
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `questionnaire-item` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def questionnaire_item(assigns) do
    ~H"""
    <fieldset
      data-slot={@rest[:"data-slot"] || "questionnaire-item"}
      class={["cn-questionnaire-item min-w-0 border-0 p-0 outline-none", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </fieldset>
    """
  end

  @doc "The `questionnaire-next` part."
  attr(:size, :string, default: "default")
  attr(:variant, :string, default: "default")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def questionnaire_next(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "questionnaire-next"}
      data-size={@size}
      data-variant={@variant}
      class={[
        "cn-questionnaire-next col-start-3 row-start-1 min-h-11 justify-self-end sm:min-h-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        Next
      <% end %>
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `questionnaire-previous` part."
  attr(:size, :string, default: "default")
  attr(:variant, :string, default: "outline")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def questionnaire_previous(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "questionnaire-previous"}
      data-size={@size}
      data-variant={@variant}
      class={[
        "cn-questionnaire-previous col-start-1 row-start-1 min-h-11 justify-self-start sm:min-h-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        Previous
      <% end %>
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `questionnaire-progress` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def questionnaire_progress(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "questionnaire-progress"}
      class={[
        "cn-questionnaire-progress min-h-[1lh] w-fit min-w-[14ch] font-medium text-muted-foreground tabular-nums",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `questionnaire-skip` part."
  attr(:size, :string, default: "default")
  attr(:variant, :string, default: "outline")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def questionnaire_skip(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "questionnaire-skip"}
      data-size={@size}
      data-variant={@variant}
      class={[
        "cn-questionnaire-skip col-start-2 row-start-1 min-h-11 justify-self-end sm:min-h-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        Skip
      <% end %>
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `questionnaire-submit` part."
  attr(:size, :string, default: "default")
  attr(:variant, :string, default: "default")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def questionnaire_submit(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "questionnaire-submit"}
      data-size={@size}
      data-variant={@variant}
      class={[
        "cn-questionnaire-submit col-start-3 row-start-1 min-h-11 justify-self-end sm:min-h-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        Submit
      <% end %>
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `questionnaire-title` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def questionnaire_title(assigns) do
    ~H"""
    <legend
      data-slot={@rest[:"data-slot"] || "questionnaire-title"}
      class={["cn-questionnaire-title cn-font-heading text-pretty", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </legend>
    """
  end
end
