defmodule LiveShadcn.UI.Sheet do
  @moduledoc """
  Sheet. Groups all parts of the dialog.

  Generated by `mix ui.gen` from `registry/spec/shadcn/sheet.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.Dialog

  @doc """
  Groups all parts of the dialog.

      <.sheet id="confirm">
        <:trigger>Delete</:trigger>
        <:title>Are you sure?</:title>
        <:description>This cannot be undone.</:description>
        Deleting removes the component and its spec.
      </.sheet>

  Opening and closing runs entirely on the client. The focus moves in when it
  opens and returns to the trigger when it closes, because a keyboard reader
  who loses their place on the page has lost the page.
  """
  attr(:id, :string, required: true, doc: "Every id inside the dialog derives from it.")
  attr(:open, :boolean, default: false, doc: "Whether it starts open.")
  attr(:alert, :boolean, default: false, doc: "An alert dialog interrupts; a dialog does not.")
  attr(:dismissable, :boolean, default: true, doc: "Whether Escape and the backdrop close it.")
  attr(:disabled, :boolean, default: false, doc: "Whether the trigger refuses interaction.")

  attr(:show_close_button, :boolean,
    default: true,
    doc: "Whether the popup draws its own close button."
  )

  attr(:class, :any, default: nil, doc: "Appended to the dialog's own class string.")
  attr(:close_class, :any, default: nil)
  attr(:description_class, :any, default: nil)
  attr(:title_class, :any, default: nil)
  attr(:trigger_class, :any, default: nil)
  attr(:side, :string, default: "right")
  attr(:rest, :global)

  slot(:trigger, required: true, doc: "What opens it.")
  slot(:title, doc: "What names it. Required for a dialog to be announced.")
  slot(:description, doc: "What describes it, beyond the title.")
  slot(:footer, doc: "Actions, along the bottom.")
  slot(:inner_block, required: true, doc: "The dialog's body.")

  def sheet(assigns) do
    ~H"""
    <div id={@id} data-slot="sheet" {@rest}>
      <button
        data-slot="sheet-trigger"
        id={Dialog.trigger_id(@id)}
        type="button"
        aria-haspopup="dialog"
        aria-expanded={to_string(@open)}
        aria-controls={Dialog.popup_id(@id)}
        phx-click={Dialog.open(@id)}
        phx-mounted={Dialog.owned_attributes(:trigger)}
        data-popup-open={flag(@open)}
        data-disabled={flag(@disabled)}
      >
        {render_slot(@trigger)}
      </button>
      <div
        data-slot="sheet-overlay"
        id={Dialog.backdrop_id(@id)}
        hidden={not @open}
        phx-click={if(@dismissable, do: Dialog.close(@id))}
        phx-mounted={Dialog.owned_attributes(:backdrop)}
        data-open={flag(@open)}
        data-closed={flag(not @open)}
        class={[
          "cn-sheet-overlay fixed inset-0 z-50 transition-opacity duration-150 data-ending-style:opacity-0 data-starting-style:opacity-0",
          @class
        ]}
        data-lb-style-target
      />
      <div
        data-slot="sheet-content"
        id={Dialog.popup_id(@id)}
        role={if(@alert, do: "alertdialog", else: "dialog")}
        aria-modal="true"
        aria-labelledby={Dialog.title_id(@id)}
        aria-describedby={Dialog.description_id(@id)}
        tabindex="-1"
        hidden={not @open}
        phx-window-keydown={if(@dismissable, do: Dialog.close(@id))}
        phx-key="Escape"
        phx-hook={Dialog.hook()}
        data-lb-backdrop={Dialog.backdrop_id(@id)}
        data-lb-modal
        phx-mounted={Dialog.owned_attributes(:popup)}
        data-open={flag(@open)}
        data-closed={flag(not @open)}
        data-side={@side}
        class={[
          "cn-sheet-content data-ending-style:opacity-0 data-starting-style:opacity-0 data-[side=bottom]:data-ending-style:translate-y-[2.5rem] data-[side=bottom]:data-starting-style:translate-y-[2.5rem] data-[side=left]:data-ending-style:translate-x-[-2.5rem] data-[side=left]:data-starting-style:translate-x-[-2.5rem] data-[side=right]:data-ending-style:translate-x-[2.5rem] data-[side=right]:data-starting-style:translate-x-[2.5rem] data-[side=top]:data-ending-style:translate-y-[-2.5rem] data-[side=top]:data-starting-style:translate-y-[-2.5rem]",
          @class
        ]}
      >
        <div data-slot="sheet-header" class="cn-sheet-header flex flex-col">
          <h2
            data-slot="sheet-title"
            id={Dialog.title_id(@id)}
            class={["cn-sheet-title cn-font-heading", @title_class]}
          >
            {render_slot(@title)}
          </h2>
          <p
            data-slot="sheet-description"
            id={Dialog.description_id(@id)}
            class={["cn-sheet-description", @description_class]}
          >
            {render_slot(@description)}
          </p>
        </div>
        {render_slot(@inner_block)}
        <div
          :if={@footer != []}
          data-slot="sheet-footer"
          class="cn-sheet-footer mt-auto flex flex-col"
        >
          {render_slot(@footer)}
        </div>
        <LiveShadcn.UI.Button.button
          :if={@show_close_button}
          data-slot="sheet-close"
          type="button"
          phx-click={Dialog.close(@id)}
          data-disabled={flag(@disabled)}
          variant="ghost"
          size="icon-sm"
          class="cn-sheet-close"
        >
          <LiveShadcn.Icon.icon name="x" />
          <span class="sr-only">
            Close
          </span>
        </LiveShadcn.UI.Button.button>
      </div>
    </div>
    """
  end

  defp flag(true), do: ""
  defp flag(_state), do: nil
end
