defmodule LiveShadcn.UI.Sidebar do
  @moduledoc """
  Sidebar.

  Generated by `mix ui.gen` from `registry/spec/shadcn/sidebar.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.Sidebar

  @doc """
  A navigation panel that collapses.

      <.sidebar id="nav" collapsible="icon">
        <.sidebar_content>…</.sidebar_content>
      </.sidebar>

  Collapsing and expanding runs entirely on the client. The server is not
  told, and does not need to be: whether a reader has the navigation open
  is a fact about their window rather than about the application's data.
  """

  attr(:id, :string, required: true, doc: "What a trigger names to open it.")
  attr(:open, :boolean, default: true, doc: "Whether it starts expanded.")
  attr(:side, :string, default: "left", values: ["left", "right"])
  attr(:variant, :string, default: "sidebar", values: ["sidebar", "floating", "inset"])

  attr(:collapsible, :string,
    default: "offcanvas",
    values: ["offcanvas", "icon"],
    doc: "What is left behind when it collapses: a strip of icons, or nothing."
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global)
  slot(:inner_block)

  def sidebar(assigns) do
    ~H"""
    <div
      id={@id}
      data-state={if(@open, do: "expanded", else: "collapsed")}
      data-collapsible={if(@open, do: "", else: @collapsible)}
      data-side={@side}
      data-variant={@variant}
      phx-mounted={Sidebar.owned_attributes(:sidebar)}
      data-slot="sidebar"
      class="group peer hidden text-sidebar-foreground md:block"
    >
      <div
        data-slot="sidebar-gap"
        class={[
          "cn-sidebar-gap relative w-(--sidebar-width) bg-transparent group-data-[collapsible=offcanvas]:w-0 group-data-[side=right]:rotate-180",
          if(@variant == "floating" || @variant == "inset",
            do: "group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)+(--spacing(4)))]",
            else: "group-data-[collapsible=icon]:w-(--sidebar-width-icon)"
          )
        ]}
      />
      <div
        data-slot={@rest[:"data-slot"] || "sidebar-container"}
        data-side={@side}
        class={[
          "fixed inset-y-0 z-10 hidden h-svh w-(--sidebar-width) transition-[left,right,width] duration-200 ease-linear data-[side=left]:left-0 data-[side=left]:group-data-[collapsible=offcanvas]:left-[calc(var(--sidebar-width)*-1)] data-[side=right]:right-0 data-[side=right]:group-data-[collapsible=offcanvas]:right-[calc(var(--sidebar-width)*-1)] md:flex",
          if(@variant == "floating" || @variant == "inset",
            do:
              "p-2 group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)+(--spacing(4))+2px)]",
            else:
              "group-data-[collapsible=icon]:w-(--sidebar-width-icon) group-data-[side=left]:border-r group-data-[side=right]:border-l"
          ),
          @class
        ]}
        {Map.drop(@rest, [:"data-slot"])}
      >
        <div
          data-slot="sidebar-inner"
          data-sidebar="sidebar"
          class="cn-sidebar-inner flex size-full flex-col"
        >
          {render_slot(@inner_block)}
        </div>
      </div>
    </div>
    """
  end

  @doc "The `sidebar-content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_content(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "sidebar-content"}
      data-sidebar="content"
      class={[
        "cn-sidebar-content flex min-h-0 flex-1 flex-col overflow-auto group-data-[collapsible=icon]:overflow-hidden",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `sidebar-footer` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_footer(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "sidebar-footer"}
      data-sidebar="footer"
      class={["cn-sidebar-footer flex flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `sidebar-group` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_group(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "sidebar-group"}
      data-sidebar="group"
      class={["cn-sidebar-group relative flex w-full min-w-0 flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `sidebar-group-action` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def sidebar_group_action(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "sidebar-group-action"}
      data-sidebar="group-action"
      class={[
        "cn-sidebar-group-action flex aspect-square items-center justify-center outline-hidden transition-transform group-data-[collapsible=icon]:hidden after:absolute after:-inset-2 md:after:hidden [&>svg]:shrink-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `sidebar-group-content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_group_content(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "sidebar-group-content"}
      data-sidebar="group-content"
      class={["cn-sidebar-group-content w-full", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `sidebar-group-label` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_group_label(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "sidebar-group-label"}
      data-sidebar="group-label"
      class={[
        "cn-sidebar-group-label flex shrink-0 items-center outline-hidden [&>svg]:shrink-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `sidebar-header` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_header(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "sidebar-header"}
      data-sidebar="header"
      class={["cn-sidebar-header flex flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `sidebar-input` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: [
      "data-slot",
      "type",
      "name",
      "value",
      "placeholder",
      "checked",
      "min",
      "max",
      "step",
      "minlength",
      "maxlength",
      "pattern",
      "readonly",
      "multiple",
      "autocomplete"
    ]
  )

  def sidebar_input(assigns) do
    ~H"""
    <LiveShadcn.UI.Input.input
      data-slot={@rest[:"data-slot"] || "sidebar-input"}
      data-sidebar="input"
      class={["cn-sidebar-input", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    />
    """
  end

  @doc "The `sidebar-inset` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_inset(assigns) do
    ~H"""
    <main
      data-slot={@rest[:"data-slot"] || "sidebar-inset"}
      class={["cn-sidebar-inset relative flex w-full flex-1 flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </main>
    """
  end

  @doc "The `sidebar-menu` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_menu(assigns) do
    ~H"""
    <ul
      data-slot={@rest[:"data-slot"] || "sidebar-menu"}
      data-sidebar="menu"
      class={["cn-sidebar-menu flex w-full min-w-0 flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </ul>
    """
  end

  @doc "The `sidebar-menu-action` part."
  attr(:show_on_hover, :boolean, default: false)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def sidebar_menu_action(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "sidebar-menu-action"}
      data-sidebar="menu-action"
      class={[
        "cn-sidebar-menu-action flex items-center justify-center outline-hidden transition-transform group-data-[collapsible=icon]:hidden after:absolute after:-inset-2 md:after:hidden [&>svg]:shrink-0",
        if(@show_on_hover,
          do:
            "group-focus-within/menu-item:opacity-100 group-hover/menu-item:opacity-100 peer-data-active/menu-button:text-sidebar-accent-foreground aria-expanded:opacity-100 md:opacity-0",
          else: nil
        ),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `sidebar-menu-badge` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_menu_badge(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "sidebar-menu-badge"}
      data-sidebar="menu-badge"
      class={[
        "cn-sidebar-menu-badge flex items-center justify-center tabular-nums select-none group-data-[collapsible=icon]:hidden",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `sidebar-menu-button` part."
  attr(:comp, :string, default: nil)
  attr(:is_active, :boolean, default: false)
  attr(:is_mobile, :string, default: nil)
  attr(:size, :string, default: "default", values: ["default", "lg", "sm"])
  attr(:state, :string, default: nil)
  attr(:tooltip, :string, default: nil)
  attr(:variant, :string, default: "default", values: ["default", "outline"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def sidebar_menu_button(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "sidebar-menu-button"}
      data-active={to_string(@is_active)}
      data-sidebar="menu-button"
      data-size={@size}
      class={[
        variant_class("sidebarMenuButtonVariants", "size", @size),
        variant_class("sidebarMenuButtonVariants", "variant", @variant),
        "cn-sidebar-menu-button peer/menu-button group/menu-button flex w-full items-center overflow-hidden outline-hidden disabled:pointer-events-none disabled:opacity-50 aria-disabled:pointer-events-none aria-disabled:opacity-50 [&_svg]:size-4 [&_svg]:shrink-0 [&>span:last-child]:truncate",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `sidebar-menu-item` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_menu_item(assigns) do
    ~H"""
    <li
      data-slot={@rest[:"data-slot"] || "sidebar-menu-item"}
      data-sidebar="menu-item"
      class={["group/menu-item relative", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </li>
    """
  end

  @doc "The `sidebar-menu-skeleton` part."
  attr(:show_icon, :boolean, default: false)
  attr(:width, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_menu_skeleton(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "sidebar-menu-skeleton"}
      data-sidebar="menu-skeleton"
      class={["cn-sidebar-menu-skeleton flex items-center", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <LiveShadcn.UI.Skeleton.skeleton
        :if={@show_icon}
        data-sidebar="menu-skeleton-icon"
        class="cn-sidebar-menu-skeleton-icon"
      />
      <LiveShadcn.UI.Skeleton.skeleton
        data-sidebar="menu-skeleton-text"
        style={"--skeleton-width: #{@width}"}
        class="cn-sidebar-menu-skeleton-text max-w-(--skeleton-width) flex-1"
      />
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `sidebar-menu-sub` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_menu_sub(assigns) do
    ~H"""
    <ul
      data-slot={@rest[:"data-slot"] || "sidebar-menu-sub"}
      data-sidebar="menu-sub"
      class={["cn-sidebar-menu-sub flex min-w-0 flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </ul>
    """
  end

  @doc "The `sidebar-menu-sub-button` part."
  attr(:is_active, :boolean, default: false)
  attr(:size, :string, default: "md", values: ["sm", "md"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "href", "target", "rel", "download", "hreflang"])
  slot(:inner_block)

  def sidebar_menu_sub_button(assigns) do
    ~H"""
    <a
      data-slot={@rest[:"data-slot"] || "sidebar-menu-sub-button"}
      data-active={to_string(@is_active)}
      data-sidebar="menu-sub-button"
      data-size={@size}
      class={[
        "cn-sidebar-menu-sub-button flex min-w-0 -translate-x-px items-center overflow-hidden outline-hidden group-data-[collapsible=icon]:hidden disabled:pointer-events-none disabled:opacity-50 aria-disabled:pointer-events-none aria-disabled:opacity-50 [&>span:last-child]:truncate [&>svg]:shrink-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </a>
    """
  end

  @doc "The `sidebar-menu-sub-item` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_menu_sub_item(assigns) do
    ~H"""
    <li
      data-slot={@rest[:"data-slot"] || "sidebar-menu-sub-item"}
      data-sidebar="menu-sub-item"
      class={["group/menu-sub-item relative", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </li>
    """
  end

  @doc "The `sidebar-provider` part."
  attr(:style, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_provider(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "sidebar-wrapper"}
      style={"--sidebar-width: 16rem; --sidebar-width-icon: 3rem; #{@style}"}
      class={[
        "group/sidebar-wrapper flex w-full has-data-[variant=inset]:bg-sidebar",
        minimum_height_class(@class),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  defp minimum_height_class(class) do
    if Enum.any?(List.wrap(class), &(is_binary(&1) and String.starts_with?(&1, "min-h-"))) do
      nil
    else
      "min-h-svh"
    end
  end

  @doc """
  The strip down the sidebar's edge, which does what the trigger does.

  It is `tabindex="-1"` and named for a screen reader, because it is a
  second way to reach a control that already has a first one.
  """

  attr(:for, :string, required: true, doc: "The id of the sidebar this opens.")
  attr(:open, :boolean, default: true, doc: "Whether that sidebar starts expanded.")

  attr(:collapsible, :string,
    default: "offcanvas",
    values: ["offcanvas", "icon"],
    doc: "The same value the sidebar was given."
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global)
  slot(:inner_block)

  def sidebar_rail(assigns) do
    ~H"""
    <button
      data-lb-sidebar={@for}
      aria-expanded={to_string(@open)}
      phx-click={Sidebar.toggle(sidebar: @for, collapsible: @collapsible)}
      phx-mounted={Sidebar.owned_attributes(:trigger)}
      data-slot={@rest[:"data-slot"] || "sidebar-rail"}
      data-sidebar="rail"
      aria-label="Toggle Sidebar"
      tabindex={-1}
      title="Toggle Sidebar"
      class={[
        "cn-sidebar-rail absolute inset-y-0 z-20 hidden w-4 transition-all ease-linear group-data-[side=left]:-right-4 group-data-[side=right]:left-0 after:absolute after:inset-y-0 after:start-1/2 after:w-[2px] sm:flex ltr:-translate-x-1/2 rtl:-translate-x-1/2 in-data-[side=left]:cursor-w-resize in-data-[side=right]:cursor-e-resize [[data-side=left][data-state=collapsed]_&]:cursor-e-resize [[data-side=right][data-state=collapsed]_&]:cursor-w-resize group-data-[collapsible=offcanvas]:translate-x-0 group-data-[collapsible=offcanvas]:after:left-full hover:group-data-[collapsible=offcanvas]:bg-sidebar [[data-side=left][data-collapsible=offcanvas]_&]:-right-2 [[data-side=right][data-collapsible=offcanvas]_&]:-left-2",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `sidebar-separator` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def sidebar_separator(assigns) do
    ~H"""
    <LiveShadcn.UI.Separator.separator
      data-slot={@rest[:"data-slot"] || "sidebar-separator"}
      data-sidebar="separator"
      class={["cn-sidebar-separator w-auto", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </LiveShadcn.UI.Separator.separator>
    """
  end

  @doc """
  The button that collapses and expands a sidebar.

      <.sidebar_trigger for="nav" collapsible="icon" />

  It names the sidebar rather than sitting inside it, because it does not:
  a trigger belongs in the header across the top of the page. React reaches
  the same fact through a context, which HEEx does not have.
  """

  attr(:for, :string, required: true, doc: "The id of the sidebar this opens.")
  attr(:open, :boolean, default: true, doc: "Whether that sidebar starts expanded.")

  attr(:collapsible, :string,
    default: "offcanvas",
    values: ["offcanvas", "icon"],
    doc: "The same value the sidebar was given."
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global)
  slot(:inner_block)

  def sidebar_trigger(assigns) do
    ~H"""
    <LiveShadcn.UI.Button.button
      data-lb-sidebar={@for}
      phx-click={Sidebar.toggle(sidebar: @for, collapsible: @collapsible)}
      phx-mounted={Sidebar.owned_attributes(:trigger)}
      data-slot={@rest[:"data-slot"] || "sidebar-trigger"}
      data-sidebar="trigger"
      variant="ghost"
      size="icon-sm"
      class={["cn-sidebar-trigger", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <LiveShadcn.Icon.icon name="panel-left" class="cn-rtl-flip" />
      <span class="sr-only">
        Toggle Sidebar
      </span>
      {render_slot(@inner_block)}
    </LiveShadcn.UI.Button.button>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "sidebarMenuButtonVariants" => %{
      "size" => %{
        "default" => "cn-sidebar-menu-button-size-default",
        "lg" => "cn-sidebar-menu-button-size-lg",
        "sm" => "cn-sidebar-menu-button-size-sm"
      },
      "variant" => %{
        "default" => "cn-sidebar-menu-button-variant-default",
        "outline" => "cn-sidebar-menu-button-variant-outline"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
