defmodule LiveShadcn.UI.Slider do
  @moduledoc """
  Slider. Groups all parts of the slider.

  Generated by `mix ui.gen` from `registry/spec/shadcn/slider.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.Slider

  @doc """
  A value between two ends, chosen by dragging.

      <.slider id="price" name="price" value={[20, 80]} />

  One `<input type="range">` per thumb, drawn. The input is what a reader
  drags, what a keyboard moves, what a screen reader announces and what a
  form submits — so `phx-change` on the form around it reports the value
  the same way a text field does, and this component has no event of its
  own.
  """

  attr(:id, :string, required: true, doc: "The hook needs one, and each input derives its own.")
  attr(:name, :string, default: nil, doc: "What the form submits every value under.")

  attr(:value, :list,
    default: [50],
    doc: "One value per thumb. Two make a range; the list's length is the number of thumbs."
  )

  attr(:min, :integer, default: 0)
  attr(:max, :integer, default: 100)
  attr(:step, :integer, default: 1)
  attr(:disabled, :boolean, default: false)
  attr(:label, :string, default: nil, doc: "Names each thumb to a screen reader.")

  attr(:orientation, :string,
    default: "horizontal",
    values: ["horizontal", "vertical"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global)

  def slider(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "slider"}
      id={@id}
      phx-hook={Slider.hook()}
      phx-mounted={Slider.owned_attributes()}
      data-orientation={@orientation}
      data-disabled={flag(@disabled)}
      class={["data-horizontal:w-full data-vertical:h-full", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <div
        data-orientation={@orientation}
        data-disabled={flag(@disabled)}
        class="cn-slider relative flex w-full touch-none items-center select-none data-disabled:opacity-50 data-vertical:h-full data-vertical:w-auto data-vertical:flex-col"
      >
        <div
          data-slot="slider-track"
          data-orientation={@orientation}
          data-disabled={flag(@disabled)}
          class="cn-slider-track relative grow overflow-hidden select-none"
        >
          <div
            data-slot="slider-range"
            data-lb-slider-range
            data-orientation={@orientation}
            data-disabled={flag(@disabled)}
            class="cn-slider-range relative select-none data-horizontal:h-full data-vertical:w-full"
          />
        </div>
        <div
          :for={index <- 0..(length(@value) - 1)//1}
          data-slot="slider-thumb"
          data-index={index}
          data-lb-slider-thumb
          style="position: absolute"
          data-orientation={@orientation}
          data-disabled={flag(@disabled)}
          class="cn-slider-thumb block shrink-0 select-none disabled:pointer-events-none disabled:opacity-50"
        >
          <input
            type="range"
            id={Slider.input_id(@id, index)}
            name={@name}
            value={Enum.at(@value, index)}
            min={@min}
            max={@max}
            step={@step}
            disabled={@disabled}
            aria-label={@label}
            data-lb-slider-input
            class="absolute inset-0 size-full cursor-pointer opacity-0 disabled:cursor-not-allowed"
          />
        </div>
      </div>
    </div>
    """
  end

  defp flag(true), do: ""
  defp flag(_state), do: nil
end
