defmodule LiveShadcn.UI.Table do
  @moduledoc """
  Table.

  Generated by `mix ui.gen` from `registry/spec/shadcn/table.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `table-container` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def table(assigns) do
    ~H"""
    <div data-slot="table-container" class="cn-table-container">
      <table
        data-slot={@rest[:"data-slot"] || "table"}
        class={["cn-table", @class]}
        {Map.drop(@rest, [:"data-slot"])}
      >
        {render_slot(@inner_block)}
      </table>
    </div>
    """
  end

  @doc "The `table-header` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def table_header(assigns) do
    ~H"""
    <thead
      data-slot={@rest[:"data-slot"] || "table-header"}
      class={["cn-table-header", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </thead>
    """
  end

  @doc "The `table-body` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def table_body(assigns) do
    ~H"""
    <tbody
      data-slot={@rest[:"data-slot"] || "table-body"}
      class={["cn-table-body", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </tbody>
    """
  end

  @doc "The `table-footer` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def table_footer(assigns) do
    ~H"""
    <tfoot
      data-slot={@rest[:"data-slot"] || "table-footer"}
      class={["cn-table-footer", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </tfoot>
    """
  end

  @doc "The `table-head` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "colspan", "rowspan", "headers", "scope", "abbr"])
  slot(:inner_block)

  def table_head(assigns) do
    ~H"""
    <th
      data-slot={@rest[:"data-slot"] || "table-head"}
      class={["cn-table-head", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </th>
    """
  end

  @doc "The `table-row` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def table_row(assigns) do
    ~H"""
    <tr
      data-slot={@rest[:"data-slot"] || "table-row"}
      class={["cn-table-row has-aria-expanded:bg-muted/50", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </tr>
    """
  end

  @doc "The `table-cell` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "colspan", "rowspan", "headers"])
  slot(:inner_block)

  def table_cell(assigns) do
    ~H"""
    <td
      data-slot={@rest[:"data-slot"] || "table-cell"}
      class={["cn-table-cell", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </td>
    """
  end

  @doc "The `table-caption` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def table_caption(assigns) do
    ~H"""
    <caption
      data-slot={@rest[:"data-slot"] || "table-caption"}
      class={["cn-table-caption", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </caption>
    """
  end
end
