defmodule LiveShadcn.UI.Tabs do
  @moduledoc """
  Tabs. Groups the tabs and the corresponding panels.

  Generated by `mix ui.gen` from `registry/spec/shadcn/tabs.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.Tabs

  @doc """
  Groups the tabs and the corresponding panels.

      <.tabs id="stages" value="spec">
        <:tab value="fetch" label="Fetch">registry/UPSTREAM.json</:tab>
        <:tab value="spec" label="Spec">registry/spec/*.json</:tab>
      </.tabs>

  Choosing a tab runs entirely on the client. Exactly one panel shows, and
  the tab that shows it is the one the arrow keys land on.
  """
  attr(:id, :string, required: true, doc: "Every id inside the tab set derives from it.")
  attr(:value, :string, default: nil, doc: "Which tab shows. Defaults to the first.")
  attr(:orientation, :string, default: "horizontal", values: ["horizontal", "vertical"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:list_class, :any, default: nil)
  attr(:content_class, :any, default: nil)
  attr(:trigger_class, :any, default: nil)
  attr(:variant, :string, default: "default", values: ["default", "line"])
  attr(:rest, :global)

  slot :tab, required: true, doc: "One tab and the panel it shows." do
    attr(:value, :string, required: true, doc: "Unique. Both ids derive from it.")
    attr(:label, :any, required: true, doc: "What the tab reads.")
    attr(:disabled, :boolean, doc: "Whether the tab refuses interaction.")
  end

  def tabs(assigns) do
    assigns = assign(assigns, :active, active(assigns))

    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "tabs"}
      id={@id}
      data-orientation={@orientation}
      data-horizontal={flag(@orientation == "horizontal")}
      class={["cn-tabs group/tabs flex data-horizontal:flex-col", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <div
        data-slot="tabs-list"
        id={@id <> "-list"}
        role="tablist"
        aria-orientation={@orientation}
        phx-hook={Tabs.hook()}
        data-lb-roving="tab"
        data-lb-orientation={@orientation}
        data-lb-loop
        data-lb-activate
        data-orientation={@orientation}
        data-variant={@variant}
        class={[
          "cn-tabs-list group/tabs-list inline-flex w-fit items-center justify-center text-muted-foreground group-data-vertical/tabs:h-fit group-data-vertical/tabs:flex-col",
          variant_class("tabsListVariants", "variant", @variant),
          @list_class
        ]}
      >
        <button
          :for={{tab, index} <- Enum.with_index(@tab)}
          data-slot="tabs-trigger"
          id={Tabs.tab_id(@id, tab[:value])}
          type="button"
          role="tab"
          aria-selected={to_string(active?(tab, @active))}
          aria-controls={Tabs.panel_id(@id, tab[:value])}
          tabindex={if(active?(tab, @active), do: "0", else: "-1")}
          phx-click={Tabs.activate(tabs: @id, value: tab[:value])}
          phx-mounted={Tabs.owned_attributes(:tab)}
          data-orientation={@orientation}
          data-disabled={flag(tab[:disabled])}
          data-active={flag(active?(tab, @active))}
          aria-disabled={to_string(tab[:disabled] == true)}
          class={[
            "cn-tabs-trigger relative inline-flex h-[calc(100%-1px)] flex-1 items-center justify-center whitespace-nowrap text-foreground/60 transition-all group-data-vertical/tabs:w-full group-data-vertical/tabs:justify-start hover:text-foreground focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1 focus-visible:outline-ring disabled:pointer-events-none disabled:opacity-50 aria-disabled:pointer-events-none aria-disabled:opacity-50 dark:text-muted-foreground dark:hover:text-foreground [&_svg]:pointer-events-none [&_svg]:shrink-0 group-data-[variant=line]/tabs-list:bg-transparent group-data-[variant=line]/tabs-list:data-active:bg-transparent dark:group-data-[variant=line]/tabs-list:data-active:border-transparent dark:group-data-[variant=line]/tabs-list:data-active:bg-transparent data-active:bg-background data-active:text-foreground dark:data-active:border-input dark:data-active:bg-input/30 dark:data-active:text-foreground after:absolute after:bg-foreground after:opacity-0 after:transition-opacity group-data-horizontal/tabs:after:inset-x-0 group-data-horizontal/tabs:after:bottom-[-5px] group-data-horizontal/tabs:after:h-0.5 group-data-vertical/tabs:after:inset-y-0 group-data-vertical/tabs:after:-right-1 group-data-vertical/tabs:after:w-0.5 group-data-[variant=line]/tabs-list:data-active:after:opacity-100",
            @trigger_class
          ]}
        >
          {tab.label}
        </button>
      </div>
      <div
        :for={{tab, index} <- Enum.with_index(@tab)}
        data-slot="tabs-content"
        id={Tabs.panel_id(@id, tab[:value])}
        role="tabpanel"
        aria-labelledby={Tabs.tab_id(@id, tab[:value])}
        tabindex="0"
        hidden={not active?(tab, @active)}
        phx-mounted={Tabs.owned_attributes(:panel)}
        data-orientation={@orientation}
        data-hidden={flag(not active?(tab, @active))}
        data-index={index}
        class={["cn-tabs-content flex-1 outline-none", @content_class]}
      >
        {render_slot(tab)}
      </div>
    </div>
    """
  end

  # Exactly one tab shows. If the caller named one, it is that one; if they
  # named nothing, it is the first, because a tab set with no panel showing
  # is a tab set that looks broken.
  defp active(%{value: nil, tab: [first | _]}), do: first[:value]
  defp active(%{value: value}), do: value

  defp active?(tab, value), do: tab[:value] == value

  defp flag(true), do: ""
  defp flag(_state), do: nil

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "tabsListVariants" => %{
      "variant" => %{
        "default" => "cn-tabs-list-variant-default bg-muted",
        "line" => "cn-tabs-list-variant-line gap-1 bg-transparent"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
