defmodule LiveShadcn.UI.Toggle do
  @moduledoc """
  Toggle. A two-state button that can be on or off.

  Generated by `mix ui.gen` from `registry/spec/shadcn/toggle.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.FormControl

  @doc """
  A two-state button that can be on or off.

      <.toggle field={@form[:bold]} />

  The control a reader sees and the input a form submits are two elements,
  as Base UI documents. Flipping one flips the other, on the client, so a
  click costs no round trip and `phx-change` still fires.

  It needs an accessible name, and a `<label for>` cannot give it one: a
  label names a labelable element, and this is not one. Name it directly:

      <.label id="subscribe-label">Send me the pull requests</.label>
      <.checkbox field={@form[:subscribe]} aria-labelledby="subscribe-label" />
  """
  attr(:field, Phoenix.HTML.FormField,
    default: nil,
    doc: "A form field. Fills in id, name, value and errors."
  )

  attr(:id, :string, default: nil)
  attr(:name, :string, default: nil)
  attr(:value, :string, default: "true", doc: "What the form submits when the control is on.")
  attr(:checked, :boolean, default: nil)
  attr(:errors, :list, default: [])
  attr(:disabled, :boolean, default: false)
  attr(:readonly, :boolean, default: false)
  attr(:required, :boolean, default: false)
  attr(:size, :string, default: "default", values: ["default", "lg", "sm"])
  attr(:variant, :string, default: "default", values: ["default", "outline"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def toggle(assigns) do
    assigns = FormControl.from_checkable(assigns)

    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "toggle"}
      id={@id}
      aria-pressed={to_string(@checked)}
      aria-disabled={to_string(@disabled)}
      phx-click={
        if(@disabled or @readonly,
          do: nil,
          else: FormControl.toggle(control: @id, state: :pressed, input: false)
        )
      }
      phx-mounted={FormControl.owned_attributes()}
      data-pressed={flag(@checked)}
      data-disabled={flag(@disabled)}
      class={[
        variant_class("toggleVariants", "size", @size),
        variant_class("toggleVariants", "variant", @variant),
        "cn-toggle group/toggle inline-flex items-center justify-center whitespace-nowrap outline-none hover:bg-muted focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  defp flag(true), do: ""
  defp flag(_state), do: nil

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "toggleVariants" => %{
      "size" => %{
        "default" => "cn-toggle-size-default",
        "lg" => "cn-toggle-size-lg",
        "sm" => "cn-toggle-size-sm"
      },
      "variant" => %{
        "default" => "cn-toggle-variant-default",
        "outline" => "cn-toggle-variant-outline"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
