defmodule LiveShadcn.UI.ToggleGroup do
  @moduledoc """
  Toggle group. Provides a shared state to a series of toggle buttons.

  Generated by `mix ui.gen` from `registry/spec/shadcn/toggle-group.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.FormControl

  @doc "The `toggle-group` part."
  attr(:orientation, :string, default: "horizontal")
  attr(:size, :string, default: nil)
  attr(:spacing, :string, default: "2")
  attr(:variant, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def toggle_group(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "toggle-group"}
      data-variant={@variant}
      data-size={@size}
      data-spacing={@spacing}
      data-orientation={@orientation}
      style={"--gap: #{@spacing}"}
      class={[
        "cn-toggle-group group/toggle-group flex w-fit flex-row items-center gap-[--spacing(var(--gap))] data-vertical:flex-col data-vertical:items-stretch",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc """
  A two-state button that can be on or off.

      <.toggle_group_item field={@form[:bold]} />

  The control a reader sees and the input a form submits are two elements,
  as Base UI documents. Flipping one flips the other, on the client, so a
  click costs no round trip and `phx-change` still fires.

  It needs an accessible name, and a `<label for>` cannot give it one: a
  label names a labelable element, and this is not one. Name it directly:

      <.label id="subscribe-label">Send me the pull requests</.label>
      <.checkbox field={@form[:subscribe]} aria-labelledby="subscribe-label" />
  """
  attr(:field, Phoenix.HTML.FormField,
    default: nil,
    doc: "A form field. Fills in id, name, value and errors."
  )

  attr(:id, :string, default: nil)
  attr(:name, :string, default: nil)
  attr(:value, :string, default: "true", doc: "What the form submits when the control is on.")
  attr(:checked, :boolean, default: nil)
  attr(:errors, :list, default: [])
  attr(:disabled, :boolean, default: false)
  attr(:readonly, :boolean, default: false)
  attr(:required, :boolean, default: false)
  attr(:context, :map, default: %{variant: nil, size: nil, spacing: nil})
  attr(:size, :string, default: "default")
  attr(:variant, :string, default: "default")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def toggle_group_item(assigns) do
    assigns = FormControl.from_checkable(assigns)

    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "toggle-group-item"}
      id={@id}
      aria-pressed={to_string(@checked)}
      aria-disabled={to_string(@disabled)}
      phx-click={
        if(@disabled or @readonly,
          do: nil,
          else: FormControl.toggle(control: @id, state: :pressed, input: false)
        )
      }
      phx-mounted={FormControl.owned_attributes()}
      data-pressed={flag(@checked)}
      data-disabled={flag(@disabled)}
      data-variant={@context.variant || @variant}
      data-size={@context.size || @size}
      data-spacing={@context.spacing}
      class={[
        "cn-toggle-group-item shrink-0 focus:z-10 focus-visible:z-10 group-data-horizontal/toggle-group:data-[spacing=0]:data-[variant=outline]:border-l-0 group-data-vertical/toggle-group:data-[spacing=0]:data-[variant=outline]:border-t-0 group-data-horizontal/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-l group-data-vertical/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-t",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  defp flag(true), do: ""
  defp flag(_state), do: nil
end
