defmodule LiveShadcn.UI.Tooltip do
  @moduledoc """
  Tooltip. Groups all parts of the tooltip.

  Generated by `mix ui.gen` from `registry/spec/shadcn/tooltip.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.Popover

  @doc """
  Groups all parts of the tooltip.

      <.tooltip id="details">
        <:trigger>Details</:trigger>
        Generated from registry/spec/accordion.json.
      </.tooltip>

  `side` and `align` are what is asked for. Where the popup lands is what
  the browser had room for, and `data-side` reports that.
  """
  attr(:id, :string, required: true, doc: "Every id inside the popover derives from it.")
  attr(:open, :boolean, default: false, doc: "Whether it starts open.")
  attr(:disabled, :boolean, default: false, doc: "Whether the trigger refuses interaction.")

  attr(:side, :string,
    default: "bottom",
    values: ["top", "right", "bottom", "left"],
    doc: "The side asked for. Where it lands is what `data-side` reports."
  )

  attr(:align, :string, default: "center", values: ["start", "center", "end"])
  attr(:offset, :integer, default: 4, doc: "The gap between the trigger and the popup.")

  attr(:autofocus, :boolean,
    default: true,
    doc: "Whether opening moves the focus into the popup. False for a tooltip."
  )

  attr(:class, :any, default: nil, doc: "Appended to the popup's class string.")
  attr(:trigger_class, :any, default: nil)
  attr(:align_offset, :string, default: "0")
  attr(:side_offset, :string, default: "4")
  attr(:rest, :global)

  slot(:trigger, required: true, doc: "What opens it.")
  slot(:inner_block, required: true, doc: "The popup's body.")

  def tooltip(assigns) do
    ~H"""
    <div
      id={@id}
      data-slot="tooltip"
      phx-window-keydown={Popover.close(@id)}
      phx-key="Escape"
      phx-click-away={Popover.dismiss(@id)}
      {@rest}
    >
      <button
        data-slot="tooltip-trigger"
        id={Popover.trigger_id(@id)}
        type="button"
        aria-haspopup="dialog"
        aria-expanded={to_string(@open)}
        aria-controls={Popover.popup_id(@id)}
        phx-click={if(not @disabled, do: Popover.toggle(@id))}
        phx-mounted={Popover.owned_attributes(:trigger)}
        data-popup-open={flag(@open)}
        data-trigger-disabled={flag(@disabled)}
      >
        {render_slot(@trigger)}
      </button>
      <div>
        <div
          id={Popover.positioner_id(@id)}
          hidden={not @open}
          phx-hook={Popover.hook()}
          data-lb-anchor={Popover.trigger_id(@id)}
          data-lb-side={@side}
          data-lb-align={@align}
          data-lb-offset={to_string(@offset)}
          data-lb-autofocus={flag(@autofocus)}
          phx-mounted={Popover.owned_attributes(:positioner)}
          data-open={flag(@open)}
          data-closed={flag(not @open)}
          class="isolate z-50"
        >
          <div
            data-slot="tooltip-content"
            id={Popover.popup_id(@id)}
            role="dialog"
            tabindex="-1"
            hidden={not @open}
            data-lb-popup
            phx-mounted={Popover.owned_attributes(:popup)}
            data-open={flag(@open)}
            data-closed={flag(not @open)}
            class={[
              "cn-tooltip-content cn-tooltip-content-logical z-50 w-fit max-w-xs origin-(--transform-origin) bg-foreground text-background",
              @class
            ]}
            data-lb-style-target
            data-lb-measure
          >
            {render_slot(@inner_block)}
            <div
              data-lb-arrow
              data-open={flag(@open)}
              data-closed={flag(not @open)}
              class="cn-tooltip-arrow cn-tooltip-arrow-logical z-50 bg-foreground fill-foreground data-[side=bottom]:top-1 data-[side=left]:top-1/2! data-[side=left]:-right-1 data-[side=left]:-translate-y-1/2 data-[side=right]:top-1/2! data-[side=right]:-left-1 data-[side=right]:-translate-y-1/2 data-[side=top]:-bottom-2.5"
              data-lb-style-target
            />
          </div>
        </div>
      </div>
    </div>
    """
  end

  defp flag(true), do: ""
  defp flag(_state), do: nil
end
