defmodule LiveAiElements.Components.Agent do
  @moduledoc """
  Agent. Built on `shadcn/accordion`, `shadcn/badge`.

  Upstream exports 1 more parts, and every one of them is a
  thin wrapper around a part of `<.accordion>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/agent.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `agent` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def agent(assigns) do
    ~H"""
    <div class={["not-prose w-full rounded-md border", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `agent_header` part."
  attr(:model, :string, default: nil)
  attr(:name, :string, default: nil)

  attr(:variant, :string,
    default: "secondary",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def agent_header(assigns) do
    ~H"""
    <div class={["flex w-full items-center justify-between gap-4 p-3", @class]} {@rest}>
      <div class="flex items-center gap-2">
        <LiveShadcn.Icon.icon name="bot" class="size-4 text-muted-foreground" />
        <span class="font-medium text-sm">
          {@name}
        </span>
        <span
          :if={@model}
          data-slot={@rest[:"data-slot"] || "badge"}
          data-variant={@variant}
          class={[
            "cn-badge group/badge inline-flex w-fit shrink-0 items-center justify-center overflow-hidden whitespace-nowrap focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none font-mono text-xs",
            variant_class("badgeVariants", "variant", @variant)
          ]}
          {Map.drop(@rest, [:"data-slot"])}
        >
          {@model}
        </span>
      </div>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `agent_content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def agent_content(assigns) do
    ~H"""
    <div class={["space-y-4 p-4 pt-0", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `agent_instructions` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def agent_instructions(assigns) do
    ~H"""
    <div class={["space-y-2", @class]} {@rest}>
      <span class="font-medium text-muted-foreground text-sm">
        Instructions
      </span>
      <div class="rounded-md bg-muted/50 p-3 text-muted-foreground text-sm">
        <p>
          {render_slot(@inner_block)}
        </p>
      </div>
    </div>
    """
  end

  @doc "The `agent_tools` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def agent_tools(assigns) do
    ~H"""
    <div class={["space-y-2", @class]}>
      <span class="font-medium text-muted-foreground text-sm">
        Tools
      </span>
      <div
        data-slot={@rest[:"data-slot"] || "accordion"}
        class="cn-accordion flex w-full flex-col rounded-md border"
        {Map.drop(@rest, [:"data-slot"])}
      >
        {render_slot(@inner_block)}
      </div>
    </div>
    """
  end

  @doc "The `agent_output` part."
  attr(:schema, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def agent_output(assigns) do
    ~H"""
    <div class={["space-y-2", @class]} {@rest}>
      <span class="font-medium text-muted-foreground text-sm">
        Output Schema
      </span>
      <div class="rounded-md bg-muted/50">
        <LiveAiElements.Components.CodeBlock.code_block code={@schema} language="typescript" />
      </div>
      {render_slot(@inner_block)}
    </div>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "badgeVariants" => %{
      "variant" => %{
        "default" => "cn-badge-variant-default",
        "destructive" => "cn-badge-variant-destructive",
        "ghost" => "cn-badge-variant-ghost",
        "link" => "cn-badge-variant-link",
        "outline" => "cn-badge-variant-outline",
        "secondary" => "cn-badge-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
