defmodule LiveAiElements.Components.Attachments do
  @moduledoc """
  Attachments. Built on `shadcn/button`.

  Upstream exports 3 more parts, each a thin
  wrapper around a part of `<.hover_card>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/attachments.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `attachments` part."
  attr(:variant, :string, default: "grid")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachments(assigns) do
    ~H"""
    <div
      class={[
        "flex items-start",
        if(@variant == "list", do: "flex-col gap-2", else: "flex-wrap gap-2"),
        if(@variant == "grid", do: "ml-auto w-fit", else: nil),
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment` part."
  attr(:data, :string, default: nil)
  attr(:variant, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment(assigns) do
    ~H"""
    <div
      class={[
        "group relative",
        if(@variant == "grid", do: "size-24 overflow-hidden rounded-lg", else: nil),
        if(@variant == "inline",
          do:
            "flex h-8 cursor-pointer select-none items-center gap-1.5 rounded-md border border-border px-1.5 font-medium text-sm transition-all hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50",
          else: nil
        ),
        if(@variant == "list",
          do: "flex w-full items-center gap-3 rounded-lg border p-3 hover:bg-accent/50",
          else: nil
        ),
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment_preview` part."
  attr(:variant, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:render_content)
  slot(:inner_block)

  def attachment_preview(assigns) do
    ~H"""
    <div
      class={[
        "flex shrink-0 items-center justify-center overflow-hidden",
        if(@variant == "grid", do: "size-full bg-muted", else: nil),
        if(@variant == "inline", do: "size-5 rounded bg-background", else: nil),
        if(@variant == "list", do: "size-12 rounded bg-muted", else: nil),
        @class
      ]}
      {@rest}
    >
      {render_slot(@render_content)}{render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment_info` part."
  attr(:data, :any, default: nil)
  attr(:label, :string, default: nil)
  attr(:show_media_type, :boolean, default: false)
  attr(:variant, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_info(assigns) do
    ~H"""
    <div :if={!(@variant == "grid")} class={["min-w-0 flex-1", @class]} {@rest}>
      <span class="block truncate">
        {@label}
      </span>
      <span
        :if={@show_media_type && @data.mediaType}
        class="block truncate text-muted-foreground text-xs"
      >
        {@data.mediaType}
      </span>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `button` part."
  attr(:label, :string, default: "Remove")

  attr(:size, :string,
    default: "default",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:variant, :string, default: "default")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def attachment_remove(assigns) do
    ~H"""
    <button
      :if={true}
      data-slot={@rest[:"data-slot"] || "button"}
      aria-label={@label}
      type="button"
      class={[
        variant_class("buttonVariants", "size", @size),
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 cn-button-variant-ghost",
        if(@variant == "grid",
          do:
            "absolute top-2 right-2 size-6 rounded-full p-0 bg-background/80 backdrop-blur-sm opacity-0 transition-opacity group-hover:opacity-100 hover:bg-background [&>svg]:size-3",
          else: nil
        ),
        if(@variant == "inline",
          do:
            "size-5 rounded p-0 opacity-0 transition-opacity group-hover:opacity-100 [&>svg]:size-2.5",
          else: nil
        ),
        if(@variant == "list", do: "size-8 shrink-0 rounded p-0 [&>svg]:size-4", else: nil),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon name="x" />
      <% end %>
      {render_slot(@inner_block)}
      <span class="sr-only">
        {@label}
      </span>
    </button>
    """
  end

  @doc "The `attachment_empty` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_empty(assigns) do
    ~H"""
    <div
      class={["flex items-center justify-center p-4 text-muted-foreground text-sm", @class]}
      {@rest}
    >
      <%= if @inner_block == [] do %>
        No attachments
      <% end %>
      {render_slot(@inner_block)}
    </div>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "size" => %{
        "default" => "cn-button-size-default",
        "icon" => "cn-button-size-icon",
        "icon-lg" => "cn-button-size-icon-lg",
        "icon-sm" => "cn-button-size-icon-sm",
        "icon-xs" => "cn-button-size-icon-xs",
        "lg" => "cn-button-size-lg",
        "sm" => "cn-button-size-sm",
        "xs" => "cn-button-size-xs"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
