defmodule LiveAiElements.Components.Attachments do
  @moduledoc """
  Attachments. Built on `shadcn/button`, `shadcn/hover-card`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/attachments.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `attachments` part."
  attr(:variant, :string, default: "grid")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachments(assigns) do
    ~H"""
    <div
      class={[
        "flex items-start",
        if(@variant == "list", do: "flex-col gap-2", else: "flex-wrap gap-2"),
        if(@variant == "grid", do: "ml-auto w-fit", else: nil),
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment` part."
  attr(:variant, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment(assigns) do
    ~H"""
    <div
      class={[
        "group relative",
        if(@variant == "grid", do: "size-24 overflow-hidden rounded-lg", else: nil),
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment_preview` part."
  attr(:variant, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:render_content)
  slot(:inner_block)

  def attachment_preview(assigns) do
    ~H"""
    <div
      class={[
        "flex shrink-0 items-center justify-center overflow-hidden",
        if(@variant == "grid", do: "size-full bg-muted", else: nil),
        if(@variant == "inline", do: "size-5 rounded bg-background", else: nil),
        if(@variant == "list", do: "size-12 rounded bg-muted", else: nil),
        @class
      ]}
      {@rest}
    >
      {render_slot(@render_content)}
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment_info` part."
  attr(:data, :any, default: nil)
  attr(:label, :string, default: nil)
  attr(:show_media_type, :boolean, default: false)
  attr(:variant, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_info(assigns) do
    ~H"""
    <div class={["min-w-0 flex-1", @class]} {@rest}>
      <span class="block truncate">
        {@label}
      </span>
      <span
        :if={@show_media_type && @data.mediaType}
        class="block truncate text-muted-foreground text-xs"
      >
        {@data.mediaType}
      </span>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `button` part."
  attr(:label, :string, default: "Remove")
  attr(:size, :string, default: "default")

  attr(:variant, :string,
    default: "default",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def attachment_remove(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "button"}
      aria-label={@label}
      type="button"
      class={[
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 cn-button-size-default",
        variant_class("buttonVariants", "variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon name="x" />
      <% end %>
      {render_slot(@inner_block)}
      <span class="sr-only">
        {@label}
      </span>
    </button>
    """
  end

  @doc "The `hover-card` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_hover_card(assigns) do
    ~H"""
    {render_slot(@inner_block)}
    """
  end

  @doc "The `hover-card-trigger` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "href", "target", "rel", "download", "hreflang"])
  slot(:inner_block)

  def attachment_hover_card_trigger(assigns) do
    ~H"""
    <a data-slot={@rest[:"data-slot"] || "hover-card-trigger"} {Map.drop(@rest, [:"data-slot"])}>
      {render_slot(@inner_block)}
    </a>
    """
  end

  @doc "The `hover-card-portal` part."
  attr(:align, :string, default: "start")
  attr(:align_offset, :string, default: "4")
  attr(:side, :string, default: "bottom")
  attr(:side_offset, :string, default: "4")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_hover_card_content(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "hover-card-portal"}
      class={["w-auto p-2", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <div
        align={@align}
        alignOffset={@align_offset}
        side={@side}
        sideOffset={@side_offset}
        class="isolate z-50"
      >
        <div
          data-slot={@rest[:"data-slot"] || "hover-card-content"}
          class={[
            "cn-hover-card-content cn-hover-card-content-logical z-50 origin-(--transform-origin) outline-hidden",
            @class
          ]}
          data-lb-measure
          {Map.drop(@rest, [:"data-slot"])}
        />
      </div>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `attachment_empty` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def attachment_empty(assigns) do
    ~H"""
    <div
      class={["flex items-center justify-center p-4 text-muted-foreground text-sm", @class]}
      {@rest}
    >
      <%= if @inner_block == [] do %>
        No attachments
      <% end %>
      {render_slot(@inner_block)}
    </div>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
