defmodule LiveAiElements.Components.AudioPlayer do
  @moduledoc """
  Audio player. Built on `shadcn/button`, `shadcn/button-group`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/audio-player.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `audio-player` part."
  attr(:style, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def audio_player(assigns) do
    ~H"""
    <media-controller
      data-slot={@rest[:"data-slot"] || "audio-player"}
      audio
      style={"--media-background-color: transparent; --media-button-icon-height: 1rem; --media-button-icon-width: 1rem; --media-control-background: transparent; --media-control-hover-background: var(--color-accent); --media-control-padding: 0; --media-font: var(--font-sans); --media-font-size: 10px; --media-icon-color: currentColor; --media-preview-time-background: var(--color-background); --media-preview-time-border-radius: var(--radius-md); --media-preview-time-text-shadow: none; --media-primary-color: var(--color-primary); --media-range-bar-color: var(--color-primary); --media-range-track-background: var(--color-secondary); --media-secondary-color: var(--color-secondary); --media-text-color: var(--color-foreground); --media-tooltip-arrow-display: none; --media-tooltip-background: var(--color-background); --media-tooltip-border-radius: var(--radius-md); #{@style}"}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </media-controller>
    """
  end

  @doc "The `audio-player-element` part."
  attr(:data, :string, default: nil)
  attr(:src, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: ["data-slot", "src", "controls", "autoplay", "loop", "muted", "preload"]
  )

  slot(:inner_block)

  def audio_player_element(assigns) do
    ~H"""
    <audio
      data-slot={@rest[:"data-slot"] || "audio-player-element"}
      slot="media"
      src={if(@src, do: @src, else: "data:#{@data.media_type};base64,#{@data.base64}")}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </audio>
    """
  end

  @doc "The `audio-player-control-bar` part."
  attr(:orientation, :string, default: "horizontal", values: ["horizontal", "vertical"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def audio_player_control_bar(assigns) do
    ~H"""
    <media-control-bar
      data-slot={@rest[:"data-slot"] || "audio-player-control-bar"}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <div
        data-slot={@rest[:"data-slot"] || "button-group"}
        role="group"
        data-orientation={@orientation}
        class={[
          variant_class("buttonGroupVariants", "orientation", @orientation),
          "cn-button-group flex w-fit items-stretch *:focus-visible:relative *:focus-visible:z-10 [&>[data-slot=select-trigger]:not([class*='w-'])]:w-fit [&>input]:flex-1"
        ]}
        {Map.drop(@rest, [:"data-slot"])}
      >
        {render_slot(@inner_block)}
      </div>
    </media-control-bar>
    """
  end

  @doc "The `audio-player-play-button` part."
  attr(:size, :string,
    default: "icon-sm",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:variant, :string,
    default: "outline",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def audio_player_play_button(assigns) do
    ~H"""
    <media-play-button
      data-slot={@rest[:"data-slot"] || "audio-player-play-button"}
      class={[
        variant_class("buttonVariants", "size", @size),
        variant_class("buttonVariants", "variant", @variant),
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 bg-transparent",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </media-play-button>
    """
  end

  @doc "The `audio-player-seek-backward-button` part."
  attr(:seek_offset, :string, default: "10")

  attr(:size, :string,
    default: "icon-sm",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:variant, :string,
    default: "outline",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def audio_player_seek_backward_button(assigns) do
    ~H"""
    <media-seek-backward-button
      data-slot={@rest[:"data-slot"] || "audio-player-seek-backward-button"}
      seekOffset={@seek_offset}
      class={[
        variant_class("buttonVariants", "size", @size),
        variant_class("buttonVariants", "variant", @variant),
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0"
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </media-seek-backward-button>
    """
  end

  @doc "The `audio-player-seek-forward-button` part."
  attr(:seek_offset, :string, default: "10")

  attr(:size, :string,
    default: "icon-sm",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:variant, :string,
    default: "outline",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def audio_player_seek_forward_button(assigns) do
    ~H"""
    <media-seek-forward-button
      data-slot={@rest[:"data-slot"] || "audio-player-seek-forward-button"}
      seekOffset={@seek_offset}
      class={[
        variant_class("buttonVariants", "size", @size),
        variant_class("buttonVariants", "variant", @variant),
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0"
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </media-seek-forward-button>
    """
  end

  @doc "The `audio-player-time-display` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def audio_player_time_display(assigns) do
    ~H"""
    <media-time-display
      data-slot={@rest[:"data-slot"] || "audio-player-time-display"}
      class={[
        "cn-button-group-text flex items-center [&_svg]:pointer-events-none bg-transparent tabular-nums",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </media-time-display>
    """
  end

  @doc "The `audio-player-time-range` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def audio_player_time_range(assigns) do
    ~H"""
    <media-time-range
      data-slot={@rest[:"data-slot"] || "audio-player-time-range"}
      class={[
        "cn-button-group-text flex items-center [&_svg]:pointer-events-none bg-transparent",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </media-time-range>
    """
  end

  @doc "The `audio-player-duration-display` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def audio_player_duration_display(assigns) do
    ~H"""
    <media-duration-display
      data-slot={@rest[:"data-slot"] || "audio-player-duration-display"}
      class={[
        "cn-button-group-text flex items-center [&_svg]:pointer-events-none bg-transparent tabular-nums",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </media-duration-display>
    """
  end

  @doc "The `audio-player-mute-button` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def audio_player_mute_button(assigns) do
    ~H"""
    <media-mute-button
      data-slot={@rest[:"data-slot"] || "audio-player-mute-button"}
      class={[
        "cn-button-group-text flex items-center [&_svg]:pointer-events-none bg-transparent",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </media-mute-button>
    """
  end

  @doc "The `audio-player-volume-range` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def audio_player_volume_range(assigns) do
    ~H"""
    <media-volume-range
      data-slot={@rest[:"data-slot"] || "audio-player-volume-range"}
      class={[
        "cn-button-group-text flex items-center [&_svg]:pointer-events-none bg-transparent",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </media-volume-range>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonGroupVariants" => %{
      "orientation" => %{
        "horizontal" =>
          "cn-button-group-orientation-horizontal *:data-slot:rounded-r-none [&>[data-slot]~[data-slot]]:rounded-l-none [&>[data-slot]~[data-slot]]:border-l-0",
        "vertical" =>
          "cn-button-group-orientation-vertical flex-col *:data-slot:rounded-b-none [&>[data-slot]~[data-slot]]:rounded-t-none [&>[data-slot]~[data-slot]]:border-t-0"
      }
    },
    "buttonVariants" => %{
      "size" => %{
        "default" => "cn-button-size-default",
        "icon" => "cn-button-size-icon",
        "icon-lg" => "cn-button-size-icon-lg",
        "icon-sm" => "cn-button-size-icon-sm",
        "icon-xs" => "cn-button-size-icon-xs",
        "lg" => "cn-button-size-lg",
        "sm" => "cn-button-size-sm",
        "xs" => "cn-button-size-xs"
      },
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
