defmodule LiveAiElements.Components.ChainOfThought do
  @moduledoc """
  Chain of thought. Built on `shadcn/badge`, `shadcn/collapsible`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/chain-of-thought.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.

  | Upstream | Digest |
  |---|---|
  | `ai_elements/chain-of-thought.tsx` | `ddc63b036299` |
  """

  use Phoenix.Component

  alias LiveBase.Disclosure

  @doc """
  Built on `shadcn/badge`, `shadcn/collapsible`.

      <.chain_of_thought id="details" title="Show details">
        The panel body.
      </.chain_of_thought>

  Opening and closing runs entirely on the client. The server is not told,
  and does not need to be: the state is whether a reader is looking at it.
  """
  attr(:id, :string, required: true, doc: "Every id inside the component derives from it.")
  attr(:title, :any, required: true, doc: "The trigger content.")

  attr(:open, :boolean,
    default: false,
    doc:
      "Whether the collapsible panel is initially open. To render a controlled collapsible, use the `open` prop instead."
  )

  attr(:disabled, :boolean,
    default: false,
    doc: "Whether the component should ignore user interaction."
  )

  attr(:orientation, :string, default: "vertical", doc: "")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:content_class, :any, default: nil, doc: "Appended to the content class string.")
  attr(:header_class, :any, default: nil, doc: "Appended to the header class string.")
  attr(:rest, :global)

  slot(:inner_block, required: true, doc: "The panel body.")

  def chain_of_thought(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "collapsible"}
      id={@id}
      data-open={flag(@open)}
      data-closed={flag(not @open)}
      open={@open}
      class={[@class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <button
        data-slot="collapsible-trigger"
        id={Disclosure.trigger_id(@id)}
        type="button"
        aria-expanded={to_string(@open)}
        aria-controls={Disclosure.panel_id(@id)}
        phx-click={interactive(@disabled, Disclosure.toggle(item: @id, root: @id, multiple: true))}
        phx-mounted={Disclosure.owned_attributes(:trigger)}
        data-panel-open={flag(@open)}
        class={[
          "flex w-full items-center gap-2 text-muted-foreground text-sm transition-colors hover:text-foreground",
          @header_class
        ]}
      >
        <LiveShadcn.Icon.icon name="brain" class="size-4" />
        <span class="flex-1 text-left">
          <%= if @title in [nil, ""] do %>
            Chain of Thought
          <% end %>
          {@title}
        </span>
        <LiveShadcn.Icon.icon
          name="chevron-down"
          class={["size-4 transition-transform", if(@open, do: "rotate-180", else: "rotate-0")]}
        />
      </button>
      <div
        data-slot="collapsible-content"
        id={Disclosure.panel_id(@id)}
        role="region"
        aria-labelledby={Disclosure.trigger_id(@id)}
        hidden={not @open}
        phx-hook={Disclosure.hook()}
        phx-mounted={Disclosure.owned_attributes(:panel)}
        data-lb-height-var="--collapsible-panel-height"
        data-lb-width-var="--collapsible-panel-width"
        data-open={flag(@open)}
        data-closed={flag(not @open)}
        class={[
          "mt-2 space-y-3 data-[state=closed]:fade-out-0 data-[state=closed]:slide-out-to-top-2 data-[state=open]:slide-in-from-top-2 text-popover-foreground outline-none data-[state=closed]:animate-out data-[state=open]:animate-in",
          @content_class
        ]}
      >
        {render_slot(@inner_block)}
      </div>
    </div>
    """
  end

  # A disabled disclosure ignores interaction. `aria-disabled` and
  # `pointer-events-none` say so to a reader and to a mouse, but a keypress
  # on a focused trigger reaches neither, so the command itself is withheld.
  defp interactive(false, command), do: command
  defp interactive(_disabled, _command), do: nil

  # An HTML attribute with no value, or no attribute at all. Base UI marks
  # state by presence, so `data-open=""` and a missing `data-open` are the
  # two states a shadcn class string distinguishes.
  defp flag(true), do: ""
  defp flag(_state), do: nil
end
