defmodule LiveAiElements.Components.Checkpoint do
  @moduledoc """
  Checkpoint. Built on `shadcn/separator`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/checkpoint.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `checkpoint` part."
  attr(:orientation, :string, default: "horizontal")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def checkpoint(assigns) do
    ~H"""
    <div class={["flex items-center gap-0.5 overflow-hidden text-muted-foreground", @class]} {@rest}>
      {render_slot(@inner_block)}
      <div
        data-slot={@rest[:"data-slot"] || "separator"}
        orientation={@orientation}
        class={[
          "shrink-0 bg-border data-horizontal:h-px data-horizontal:w-full data-vertical:w-px data-vertical:self-stretch",
          @class
        ]}
        {Map.drop(@rest, [:"data-slot"])}
      />
    </div>
    """
  end
end
