defmodule LiveAiElements.Components.Checkpoint do
  @moduledoc """
  Checkpoint. Built on `shadcn/button`, `shadcn/separator`, `shadcn/tooltip`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/checkpoint.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `checkpoint` part."
  attr(:orientation, :string, default: "horizontal")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def checkpoint(assigns) do
    ~H"""
    <div class={["flex items-center gap-0.5 overflow-hidden text-muted-foreground", @class]} {@rest}>
      {render_slot(@inner_block)}
      <div
        data-slot={@rest[:"data-slot"] || "separator"}
        orientation={@orientation}
        class={[
          "shrink-0 bg-border data-horizontal:h-px data-horizontal:w-full data-vertical:w-px data-vertical:self-stretch",
          @class
        ]}
        {Map.drop(@rest, [:"data-slot"])}
      />
    </div>
    """
  end

  @doc "The `checkpoint_icon` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def checkpoint_icon(assigns) do
    ~H"""
    <%= if @inner_block == [] do %>
      <LiveShadcn.Icon.icon name="bookmark" class={["size-4 shrink-0", @class]} {@rest} />
    <% end %>
    {render_slot(@inner_block)}
    """
  end

  @doc "The `checkpoint_trigger` part."
  attr(:align, :string, default: "center")
  attr(:align_offset, :string, default: "0")
  attr(:side, :string, default: "top")
  attr(:side_offset, :string, default: "4")

  attr(:size, :string,
    default: "sm",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:tooltip, :string, default: nil)

  attr(:variant, :string,
    default: "ghost",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])

  def checkpoint_trigger(assigns) do
    ~H"""
    <button data-slot={@rest[:"data-slot"] || "tooltip-trigger"} {Map.drop(@rest, [:"data-slot"])}>
      <button
        data-slot={@rest[:"data-slot"] || "button"}
        type="button"
        class={[
          "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
          variant_class("buttonVariants", "size", @size),
          variant_class("buttonVariants", "variant", @variant),
          @class
        ]}
        {Map.drop(@rest, [:"data-slot"])}
      >
        {render_slot(@inner_block)}
      </button>
    </button>
    <div>
      <div
        align={@align}
        alignOffset={@align_offset}
        side={@side}
        sideOffset={@side_offset}
        class="isolate z-50"
      >
        <div
          data-slot={@rest[:"data-slot"] || "tooltip-content"}
          class={[
            "cn-tooltip-content cn-tooltip-content-logical z-50 w-fit max-w-xs origin-(--transform-origin) bg-foreground text-background",
            @class
          ]}
          {Map.drop(@rest, [:"data-slot"])}
        >
          {@tooltip}
          <div class="cn-tooltip-arrow cn-tooltip-arrow-logical z-50 bg-foreground fill-foreground data-[side=bottom]:top-1 data-[side=left]:top-1/2! data-[side=left]:-right-1 data-[side=left]:-translate-y-1/2 data-[side=right]:top-1/2! data-[side=right]:-left-1 data-[side=right]:-translate-y-1/2 data-[side=top]:-bottom-2.5" />
        </div>
      </div>
    </div>
    <button
      :if={!@tooltip}
      data-slot={@rest[:"data-slot"] || "button"}
      type="button"
      class={[
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
        variant_class("buttonVariants", "size", @size),
        variant_class("buttonVariants", "variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "size" => %{
        "default" => "cn-button-size-default",
        "icon" => "cn-button-size-icon",
        "icon-lg" => "cn-button-size-icon-lg",
        "icon-sm" => "cn-button-size-icon-sm",
        "icon-xs" => "cn-button-size-icon-xs",
        "lg" => "cn-button-size-lg",
        "sm" => "cn-button-size-sm",
        "xs" => "cn-button-size-xs"
      },
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
