defmodule LiveAiElements.Components.CodeBlock do
  @moduledoc """
  Code block. Built on `shadcn/button`.

  Upstream exports 5 more parts, each a thin
  wrapper around a part of `<.select>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/code-block.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `code_block_container` part."
  attr(:language, :string, default: nil)
  attr(:style, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def code_block_container(assigns) do
    ~H"""
    <div
      data-language={@language}
      style={"#{@style}; contain-intrinsic-size: auto 200px; content-visibility: auto"}
      class={[
        "group relative w-full overflow-hidden rounded-md border bg-background text-foreground",
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `code_block_header` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def code_block_header(assigns) do
    ~H"""
    <div
      class={[
        "flex items-center justify-between border-b bg-muted/80 px-3 py-2 text-muted-foreground text-xs",
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `code_block_title` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def code_block_title(assigns) do
    ~H"""
    <div class={["flex items-center gap-2", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `code_block_filename` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def code_block_filename(assigns) do
    ~H"""
    <span class={["font-mono", @class]} {@rest}>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `code_block_actions` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def code_block_actions(assigns) do
    ~H"""
    <div class={["-my-1 -mr-1 flex items-center gap-2", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `code_block_content` part."
  attr(:code, :string, default: nil)
  attr(:keyed_line, :any, default: nil)
  attr(:keyed_lines, :any, default: nil)
  attr(:language, :string, default: nil)
  attr(:pre_style, :string, default: nil)
  attr(:show_line_numbers, :boolean, default: false)
  attr(:token, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def code_block_content(assigns) do
    ~H"""
    <div class="relative overflow-auto">
      <pre
        style=""
        class={[
          "dark:!bg-[var(--shiki-dark-bg)] dark:!text-[var(--shiki-dark)] m-0 p-4 text-sm",
          @class
        ]}
      ><code class={["font-mono text-sm", if(@show_line_numbers, do: "[counter-increment:line_0] [counter-reset:line]", else: nil)]}>
      <span :for={keyedLine <- @keyed_lines} class={[if(@show_line_numbers, do: "block before:content-[counter(line)] before:inline-block before:[counter-increment:line] before:w-8 before:mr-4 before:text-right before:text-muted-foreground/50 before:font-mono before:select-none", else: "block")]}>
        \n
        <span :if={!(length(keyedLine.tokens) == 0)} :for={item <- keyedLine.tokens} style={"background-color: #{item.token.bgColor}; color: #{item.token.color}; font-style: #{if(Bitwise.band(item.token.fontStyle || 0, 1) != 0, do: "italic", else: nil)}; font-weight: #{if(Bitwise.band(item.token.fontStyle || 0, 2) != 0, do: "bold", else: nil)}; text-decoration: #{if(Bitwise.band(item.token.fontStyle || 0, 4) != 0, do: "underline", else: nil)}"} class="dark:!bg-[var(--shiki-dark-bg)] dark:!text-[var(--shiki-dark)]">
          {item.token.content}
        </span>
      </span>
    </code></pre>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `code_block` part."
  attr(:code, :string, default: nil)
  attr(:language, :string, default: nil)
  attr(:show_line_numbers, :boolean, default: false)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def code_block(assigns) do
    ~H"""
    <.code_block_container language={@language} class={[@class]} {@rest}>
      {render_slot(@inner_block)}
      <.code_block_content code={@code} language={@language} show_line_numbers={@show_line_numbers} />
    </.code_block_container>
    """
  end

  @doc "The `button` part."
  attr(:size, :string,
    default: "icon",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:timeout, :any, default: 2000)

  attr(:variant, :string,
    default: "ghost",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:id, :string, required: true, doc: "The hook needs one to be found by.")
  attr(:code, :string, required: true, doc: "The code the button copies.")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def code_block_copy_button(assigns) do
    ~H"""
    <button
      id={@id}
      phx-hook={LiveBase.Clipboard.hook()}
      phx-mounted={LiveBase.Clipboard.owned_attributes()}
      data-lb-clipboard={@code}
      data-lb-timeout={@timeout}
      data-slot={@rest[:"data-slot"] || "button"}
      class={[
        variant_class("buttonVariants", "size", @size),
        variant_class("buttonVariants", "variant", @variant),
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 shrink-0",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon data-lb-state="copied" hidden name="check" width="14" height="14" />
        <LiveShadcn.Icon.icon data-lb-state="idle" name="copy" width="14" height="14" />
      <% end %>
      {render_slot(@inner_block)}
    </button>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "size" => %{
        "default" => "cn-button-size-default",
        "icon" => "cn-button-size-icon",
        "icon-lg" => "cn-button-size-icon-lg",
        "icon-sm" => "cn-button-size-icon-sm",
        "icon-xs" => "cn-button-size-icon-xs",
        "lg" => "cn-button-size-lg",
        "sm" => "cn-button-size-sm",
        "xs" => "cn-button-size-xs"
      },
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
