defmodule LiveAiElements.Components.Commit do
  @moduledoc """
  Commit.

  Upstream exports 2 more parts, each a thin
  wrapper around a part of `<.collapsible>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/commit.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `commit_header` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_header(assigns) do
    ~H"""
    <div
      class={[
        "group flex cursor-pointer items-center justify-between gap-4 p-3 text-left transition-colors hover:opacity-80",
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `commit_hash` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_hash(assigns) do
    ~H"""
    <span class={["font-mono text-xs", @class]} {@rest}>
      <LiveShadcn.Icon.icon name="git-commit-horizontal" class="mr-1 inline-block size-3" />{render_slot(
        @inner_block
      )}
    </span>
    """
  end

  @doc "The `commit_message` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_message(assigns) do
    ~H"""
    <span class={["font-medium text-sm", @class]} {@rest}>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `commit_metadata` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_metadata(assigns) do
    ~H"""
    <div class={["flex items-center gap-2 text-muted-foreground text-xs", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `commit_separator` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_separator(assigns) do
    ~H"""
    <span class={[@class]} {@rest}>
      <%= if @inner_block == [] do %>
        •
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `commit_info` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_info(assigns) do
    ~H"""
    <div class={["flex flex-1 flex-col", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `commit_author` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_author(assigns) do
    ~H"""
    <div class={["flex items-center", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `commit_author_avatar` part."
  attr(:initials, :string, default: nil)
  attr(:size, :string, default: "default")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_author_avatar(assigns) do
    ~H"""
    <LiveShadcn.UI.Avatar.avatar size={@size} class={["size-8", @class]} {@rest}>
      <LiveShadcn.UI.Avatar.avatar_fallback class="text-xs">
        {@initials}
      </LiveShadcn.UI.Avatar.avatar_fallback>
      {render_slot(@inner_block)}
    </LiveShadcn.UI.Avatar.avatar>
    """
  end

  @doc "The `commit_timestamp` part."
  attr(:date, :any, default: nil)
  attr(:formatted, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "datetime"])
  slot(:inner_block)

  def commit_timestamp(assigns) do
    ~H"""
    <time datetime={@date} class={["text-xs", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        {@formatted}
      <% end %>
      {render_slot(@inner_block)}
    </time>
    """
  end

  @doc "The `commit_actions` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_actions(assigns) do
    ~H"""
    <div role="group" class={["flex items-center gap-1", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `commit_copy_button` part."
  attr(:hash, :string, default: nil)
  attr(:size, :string, default: "icon")
  attr(:timeout, :any, default: 2000)
  attr(:variant, :string, default: "ghost")
  attr(:id, :string, required: true, doc: "The hook needs one to be found by.")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction", "disabled"])
  slot(:inner_block)

  def commit_copy_button(assigns) do
    ~H"""
    <LiveShadcn.UI.Button.button
      id={@id}
      phx-hook={LiveBase.Clipboard.hook()}
      phx-mounted={LiveBase.Clipboard.owned_attributes()}
      data-lb-clipboard={@hash}
      data-lb-timeout={@timeout}
      size={@size}
      variant={@variant}
      class={["size-7 shrink-0", @class]}
      {@rest}
    >
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon data-lb-state="copied" hidden name="check" width="14" height="14" />
        <LiveShadcn.Icon.icon data-lb-state="idle" name="copy" width="14" height="14" />
      <% end %>
      {render_slot(@inner_block)}
    </LiveShadcn.UI.Button.button>
    """
  end

  @doc "The `commit_files` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_files(assigns) do
    ~H"""
    <div class={["space-y-1", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `commit_file` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_file(assigns) do
    ~H"""
    <div
      class={[
        "flex items-center justify-between gap-2 rounded px-2 py-1 text-sm hover:bg-muted/50",
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `commit_file_info` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_file_info(assigns) do
    ~H"""
    <div class={["flex min-w-0 items-center gap-2", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `commit_file_status` part."
  attr(:status, :string, default: nil, values: [nil, "added", "modified", "deleted", "renamed"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_file_status(assigns) do
    ~H"""
    <span
      class={[
        "font-medium font-mono text-xs",
        if(@status == "added", do: "text-green-600 dark:text-green-400", else: nil),
        if(@status == "deleted", do: "text-red-600 dark:text-red-400", else: nil),
        if(@status == "modified", do: "text-yellow-600 dark:text-yellow-400", else: nil),
        if(@status == "renamed", do: "text-blue-600 dark:text-blue-400", else: nil),
        @class
      ]}
      {@rest}
    >
      <%= if @inner_block == [] do %>
        {Map.get(%{"added" => "A", "deleted" => "D", "modified" => "M", "renamed" => "R"}, @status)}
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `commit_file_icon` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_file_icon(assigns) do
    ~H"""
    <LiveShadcn.Icon.icon
      name="file"
      class={["size-3.5 shrink-0 text-muted-foreground", @class]}
      {@rest}
    />
    """
  end

  @doc "The `commit_file_path` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_file_path(assigns) do
    ~H"""
    <span class={["truncate font-mono text-xs", @class]} {@rest}>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `commit_file_changes` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_file_changes(assigns) do
    ~H"""
    <div class={["flex shrink-0 items-center gap-1 font-mono text-xs", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `commit_file_additions` part."
  attr(:count, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_file_additions(assigns) do
    ~H"""
    <span :if={!(@count <= 0)} class={["text-green-600 dark:text-green-400", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon name="plus" class="inline-block size-3" />{@count}
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `commit_file_deletions` part."
  attr(:count, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def commit_file_deletions(assigns) do
    ~H"""
    <span :if={!(@count <= 0)} class={["text-red-600 dark:text-red-400", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon name="minus" class="inline-block size-3" />{@count}
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end
end
