defmodule LiveAiElements.Components.Confirmation do
  @moduledoc """
  Confirmation. Built on `shadcn/alert`, `shadcn/button`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/confirmation.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `confirmation` part."
  attr(:variant, :string, default: "default", values: ["default", "destructive"])
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def confirmation(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "alert"}
      role="alert"
      class={[
        "cn-alert group/alert relative w-full flex flex-col gap-2",
        variant_class("variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `alert-description` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def confirmation_title(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "alert-description"}
      class={[
        "cn-alert-description [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground inline",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `confirmation_request` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def confirmation_request(assigns) do
    ~H"""
    {render_slot(@inner_block)}
    """
  end

  @doc "The `confirmation_accepted` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def confirmation_accepted(assigns) do
    ~H"""
    {render_slot(@inner_block)}
    """
  end

  @doc "The `confirmation_rejected` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def confirmation_rejected(assigns) do
    ~H"""
    {render_slot(@inner_block)}
    """
  end

  @doc "The `confirmation_actions` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def confirmation_actions(assigns) do
    ~H"""
    <div class={["flex items-center justify-end gap-2 self-end", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `button` part."
  attr(:size, :string,
    default: "default",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:variant, :string,
    default: "default",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def confirmation_action(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "button"}
      type="button"
      class={[
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 h-8 px-3 text-sm",
        variant_class("size", @size),
        variant_class("variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  # The variant table, from the `cva` call upstream writes it in.
  @variants %{
    "size" => %{
      "default" => "cn-button-size-default",
      "icon" => "cn-button-size-icon",
      "icon-lg" => "cn-button-size-icon-lg",
      "icon-sm" => "cn-button-size-icon-sm",
      "icon-xs" => "cn-button-size-icon-xs",
      "lg" => "cn-button-size-lg",
      "sm" => "cn-button-size-sm",
      "xs" => "cn-button-size-xs"
    },
    "variant" => %{
      "default" => "cn-button-variant-default",
      "destructive" => "cn-button-variant-destructive",
      "ghost" => "cn-button-variant-ghost",
      "link" => "cn-button-variant-link",
      "outline" => "cn-button-variant-outline",
      "secondary" => "cn-button-variant-secondary"
    }
  }

  defp variant_class(group, value), do: get_in(@variants, [group, value])
end
