defmodule LiveAiElements.Components.Connection do
  @moduledoc """
  Connection.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/connection.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `connection` part."
  attr(:from_x, :any, default: nil)
  attr(:from_y, :any, default: nil)
  attr(:to_x, :any, default: nil)
  attr(:to_y, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def connection(assigns) do
    ~H"""
    <g>
      <path
        d={"M#{@from_x},#{@from_y} C #{@from_x + ((@to_x - @from_x) * 0.5)},#{@from_y} #{@from_x + ((@to_x - @from_x) * 0.5)},#{@to_y} #{@to_x},#{@to_y}"}
        fill="none"
        stroke="var(--color-ring)"
        stroke-width={1}
        class="animated"
      />
      <circle cx={@to_x} cy={@to_y} fill="#fff" r={3} stroke="var(--color-ring)" stroke-width={1} />
      {render_slot(@inner_block)}
    </g>
    """
  end
end
