defmodule LiveAiElements.Components.Context do
  @moduledoc """
  Context. Built on `shadcn/hover-card`, `shadcn/progress`.

  Upstream exports 3 more parts, and every one of them is a
  thin wrapper around a part of `<.hover_card>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/context.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `context_content_header` part."
  attr(:display_pct, :string, default: nil)
  attr(:total, :string, default: nil)
  attr(:used, :string, default: nil)
  attr(:used_percent, :string, default: nil)
  attr(:value, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def context_content_header(assigns) do
    ~H"""
    <div class={["w-full space-y-2 p-3", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        <div class="flex items-center justify-between gap-3 text-xs">
          <p>
            {@display_pct}
          </p>
          <p class="font-mono text-muted-foreground">
            {@used} / {@total}
          </p>
        </div>
        <div class="space-y-2">
          <div
            data-slot={@rest[:"data-slot"] || "progress"}
            value={@value}
            class="cn-progress-root flex flex-wrap gap-3 bg-muted"
            {Map.drop(@rest, [:"data-slot"])}
          >
            <div
              data-slot={@rest[:"data-slot"] || "progress-track"}
              class={["cn-progress-track relative flex w-full items-center overflow-x-hidden", @class]}
              {Map.drop(@rest, [:"data-slot"])}
            >
              <div
                data-slot={@rest[:"data-slot"] || "progress-indicator"}
                class={["cn-progress-indicator h-full transition-all", @class]}
                {Map.drop(@rest, [:"data-slot"])}
              />
            </div>
          </div>
        </div>
      <% end %>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `context_content_body` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def context_content_body(assigns) do
    ~H"""
    <div class={["w-full p-3", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `context_content_footer` part."
  attr(:total_cost, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def context_content_footer(assigns) do
    ~H"""
    <div
      class={["flex w-full items-center justify-between gap-3 bg-secondary p-3 text-xs", @class]}
      {@rest}
    >
      <%= if @inner_block == [] do %>
        <span class="text-muted-foreground">
          Total cost
        </span>
        <span>
          {@total_cost}
        </span>
      <% end %>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `context_input_usage` part."
  attr(:cost_text, :string, default: nil)
  attr(:input_cost_text, :string, default: nil)
  attr(:input_tokens, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def context_input_usage(assigns) do
    ~H"""
    <div class={["flex items-center justify-between text-xs", @class]} {@rest}>
      <span class="text-muted-foreground">
        Input
      </span>
      <span>
        {if(is_nil(@input_tokens), do: "—", else: compact_number(@input_tokens))}
        <span :if={@input_cost_text} class="ml-2 text-muted-foreground">
          • {@input_cost_text}
        </span>
        {nil}
      </span>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `context_output_usage` part."
  attr(:cost_text, :string, default: nil)
  attr(:output_cost_text, :string, default: nil)
  attr(:output_tokens, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def context_output_usage(assigns) do
    ~H"""
    <div class={["flex items-center justify-between text-xs", @class]} {@rest}>
      <span class="text-muted-foreground">
        Output
      </span>
      <span>
        {if(is_nil(@output_tokens), do: "—", else: compact_number(@output_tokens))}
        <span :if={@output_cost_text} class="ml-2 text-muted-foreground">
          • {@output_cost_text}
        </span>
        {nil}
      </span>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `context_reasoning_usage` part."
  attr(:cost_text, :string, default: nil)
  attr(:reasoning_cost_text, :string, default: nil)
  attr(:reasoning_tokens, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def context_reasoning_usage(assigns) do
    ~H"""
    <div class={["flex items-center justify-between text-xs", @class]} {@rest}>
      <span class="text-muted-foreground">
        Reasoning
      </span>
      <span>
        {if(is_nil(@reasoning_tokens), do: "—", else: compact_number(@reasoning_tokens))}
        <span :if={@reasoning_cost_text} class="ml-2 text-muted-foreground">
          • {@reasoning_cost_text}
        </span>
        {nil}
      </span>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `context_cache_usage` part."
  attr(:cache_cost_text, :string, default: nil)
  attr(:cache_tokens, :any, default: nil)
  attr(:cost_text, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def context_cache_usage(assigns) do
    ~H"""
    <div class={["flex items-center justify-between text-xs", @class]} {@rest}>
      <span class="text-muted-foreground">
        Cache
      </span>
      <span>
        {if(is_nil(@cache_tokens), do: "—", else: compact_number(@cache_tokens))}
        <span :if={@cache_cost_text} class="ml-2 text-muted-foreground">
          • {@cache_cost_text}
        </span>
        {nil}
      </span>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc false
  defp compact_number(number) when is_number(number) do
    {value, suffix} = compact_parts(number)
    whole = trunc(value)

    if value == whole, do: "#{whole}#{suffix}", else: "#{value}#{suffix}"
  end

  defp compact_number(_number), do: nil

  defp compact_parts(number) do
    {value, suffix} =
      cond do
        abs(number) >= 1.0e9 -> {number / 1.0e9, "B"}
        abs(number) >= 1.0e6 -> {number / 1.0e6, "M"}
        abs(number) >= 1.0e3 -> {number / 1.0e3, "K"}
        true -> {number * 1.0, ""}
      end

    rounded = Float.round(value, if(abs(value) < 10, do: 1, else: 0))

    if abs(rounded) >= 1000 and suffix != "B",
      do: compact_parts(round(rounded * 1000)),
      else: {rounded, suffix}
  end
end
