defmodule LiveAiElements.Components.EnvironmentVariables do
  @moduledoc """
  Environment variables. Built on `shadcn/badge`, `shadcn/button`, `shadcn/switch`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/environment-variables.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `environment_variables` part."
  attr(:default_show_values, :boolean, default: false)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variables(assigns) do
    ~H"""
    <div class={["rounded-lg border bg-background", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `environment_variables_header` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variables_header(assigns) do
    ~H"""
    <div class={["flex items-center justify-between border-b px-4 py-3", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `environment_variables_title` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variables_title(assigns) do
    ~H"""
    <h3 class={["font-medium text-sm", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        Environment Variables
      <% end %>
      {render_slot(@inner_block)}
    </h3>
    """
  end

  @doc "The `environment_variables_toggle` part."
  attr(:show_values, :boolean, default: nil)
  attr(:size, :string, default: "default")

  attr(:on_toggle, :any,
    default: nil,
    doc:
      "Pushed when the switch is flipped. The server owns `show_values`, because the value it reveals is a secret."
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variables_toggle(assigns) do
    ~H"""
    <div class={["flex items-center gap-2", @class]}>
      <span class="text-muted-foreground text-xs">
        <LiveShadcn.Icon.icon :if={@show_values} name="eye" />
        <LiveShadcn.Icon.icon :if={!@show_values} name="eye-off" />
      </span>
      <span
        role="switch"
        tabindex="0"
        aria-checked={to_string(@show_values == true)}
        phx-click={@on_toggle}
        phx-keydown={@on_toggle}
        phx-key=" "
        data-checked={if(@show_values == true, do: "")}
        data-unchecked={if(@show_values != true, do: "")}
        data-slot={@rest[:"data-slot"] || "switch"}
        data-size={@size}
        aria-label="Toggle value visibility"
        class={[
          "cn-switch peer group/switch relative inline-flex items-center transition-all outline-none after:absolute after:-inset-x-3 after:-inset-y-2 data-disabled:cursor-not-allowed data-disabled:opacity-50",
          @class
        ]}
        {Map.drop(@rest, [:"data-slot"])}
      >
        <span
          data-checked={if(@show_values == true, do: "")}
          data-unchecked={if(@show_values != true, do: "")}
          data-slot="switch-thumb"
          class="cn-switch-thumb pointer-events-none block ring-0 transition-transform"
        />
        {render_slot(@inner_block)}
      </span>
    </div>
    """
  end

  @doc "The `environment_variables_content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variables_content(assigns) do
    ~H"""
    <div class={["divide-y", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `environment_variable_group` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variable_group(assigns) do
    ~H"""
    <div class={["flex items-center gap-2", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `environment_variable_name` part."
  attr(:name, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variable_name(assigns) do
    ~H"""
    <span class={["font-mono text-sm", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        {@name}
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `environment_variable_value` part."
  attr(:display_value, :string, default: nil)
  attr(:show_values, :boolean, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variable_value(assigns) do
    ~H"""
    <span
      class={[
        "font-mono text-muted-foreground text-sm",
        if(!@show_values, do: "select-none", else: nil),
        @class
      ]}
      {@rest}
    >
      <%= if @inner_block == [] do %>
        {@display_value}
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `environment_variable` part."
  attr(:name, :string, default: nil)
  attr(:value, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variable(assigns) do
    ~H"""
    <div class={["flex items-center justify-between gap-4 px-4 py-3", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        <div class="flex items-center gap-2">
          <.environment_variable_name />
        </div>
        <.environment_variable_value />
      <% end %>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `button` part."
  attr(:copy_format, :string, default: "value", values: ["name", "value", "export"])

  attr(:size, :string,
    default: "default",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:timeout, :any, default: "2000")

  attr(:variant, :string,
    default: "default",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:id, :string, required: true, doc: "The hook needs one to be found by.")
  attr(:name, :string, required: true, doc: "The variable's name.")
  attr(:value, :string, required: true, doc: "The variable's value.")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def environment_variable_copy_button(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "button"}
      id={@id}
      phx-hook={LiveBase.Clipboard.hook()}
      phx-mounted={LiveBase.Clipboard.owned_attributes()}
      data-lb-clipboard={
        Map.get(%{"name" => @name, "export" => "export #{@name}=\"#{@value}\""}, @copy_format, @value)
      }
      data-lb-timeout={@timeout}
      class={[
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 size-6 shrink-0",
        variant_class("buttonVariants", "size", @size),
        variant_class("buttonVariants", "variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon data-lb-state="copied" hidden name="check" />
        <LiveShadcn.Icon.icon data-lb-state="idle" name="copy" />
      <% end %>
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `badge` part."
  attr(:variant, :string,
    default: "default",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variable_required(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "badge"}
      data-variant={@variant}
      class={[
        "cn-badge group/badge inline-flex w-fit shrink-0 items-center justify-center overflow-hidden whitespace-nowrap focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none text-xs",
        variant_class("badgeVariants", "variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        Required
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "badgeVariants" => %{
      "variant" => %{
        "default" => "cn-badge-variant-default",
        "destructive" => "cn-badge-variant-destructive",
        "ghost" => "cn-badge-variant-ghost",
        "link" => "cn-badge-variant-link",
        "outline" => "cn-badge-variant-outline",
        "secondary" => "cn-badge-variant-secondary"
      }
    },
    "buttonVariants" => %{
      "size" => %{
        "default" => "cn-button-size-default",
        "icon" => "cn-button-size-icon",
        "icon-lg" => "cn-button-size-icon-lg",
        "icon-sm" => "cn-button-size-icon-sm",
        "icon-xs" => "cn-button-size-icon-xs",
        "lg" => "cn-button-size-lg",
        "sm" => "cn-button-size-sm",
        "xs" => "cn-button-size-xs"
      },
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
