defmodule LiveAiElements.Components.EnvironmentVariables do
  @moduledoc """
  Environment variables. Built on `shadcn/switch`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/environment-variables.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `environment_variables` part."
  attr(:default_show_values, :boolean, default: false)
  attr(:show_values, :boolean, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variables(assigns) do
    ~H"""
    <div class={["rounded-lg border bg-background", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `environment_variables_header` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variables_header(assigns) do
    ~H"""
    <div class={["flex items-center justify-between border-b px-4 py-3", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `environment_variables_title` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variables_title(assigns) do
    ~H"""
    <h3 class={["font-medium text-sm", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        Environment Variables
      <% end %>
      {render_slot(@inner_block)}
    </h3>
    """
  end

  @doc "The `environment_variables_toggle` part."
  attr(:show_values, :boolean, default: nil)
  attr(:size, :string, default: "default")

  attr(:on_toggle, :any,
    default: nil,
    doc:
      "Pushed when the switch is flipped. The server owns `show_values`, because the value it reveals is a secret."
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variables_toggle(assigns) do
    ~H"""
    <div class={["flex items-center gap-2", @class]}>
      <span class="text-muted-foreground text-xs">
        <LiveShadcn.Icon.icon :if={@show_values} name="eye" width="14" height="14" />
        <LiveShadcn.Icon.icon :if={!@show_values} name="eye-off" width="14" height="14" />
      </span>
      <span
        role="switch"
        tabindex="0"
        aria-checked={to_string(@show_values == true)}
        phx-click={@on_toggle}
        phx-keydown={@on_toggle}
        phx-key=" "
        data-checked={if(@show_values == true, do: "")}
        data-unchecked={if(@show_values != true, do: "")}
        data-slot={@rest[:"data-slot"] || "switch"}
        data-size={@size}
        aria-label="Toggle value visibility"
        class="cn-switch peer group/switch relative inline-flex items-center transition-all outline-none after:absolute after:-inset-x-3 after:-inset-y-2 data-disabled:cursor-not-allowed data-disabled:opacity-50"
        {Map.drop(@rest, [:"data-slot"])}
      >
        <span
          data-checked={if(@show_values == true, do: "")}
          data-unchecked={if(@show_values != true, do: "")}
          data-slot="switch-thumb"
          class="cn-switch-thumb pointer-events-none block ring-0 transition-transform"
        />
        {render_slot(@inner_block)}
      </span>
    </div>
    """
  end

  @doc "The `environment_variables_content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variables_content(assigns) do
    ~H"""
    <div class={["divide-y", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `environment_variable_group` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variable_group(assigns) do
    ~H"""
    <div class={["flex items-center gap-2", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `environment_variable_name` part."
  attr(:name, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variable_name(assigns) do
    ~H"""
    <span class={["font-mono text-sm", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        {@name}
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `environment_variable_value` part."
  attr(:display_value, :string, default: nil)
  attr(:show_values, :boolean, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variable_value(assigns) do
    ~H"""
    <span
      class={[
        "font-mono text-muted-foreground text-sm",
        if(!@show_values, do: "select-none", else: nil),
        @class
      ]}
      {@rest}
    >
      <%= if @inner_block == [] do %>
        {@display_value}
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `environment_variable` part."
  attr(:name, :string, default: nil)
  attr(:value, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variable(assigns) do
    ~H"""
    <div class={["flex items-center justify-between gap-4 px-4 py-3", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        <div class="flex items-center gap-2">
          <.environment_variable_name name={@name} />
        </div>
        <.environment_variable_value />
      <% end %>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `environment_variable_copy_button` part."
  attr(:copy_format, :string, default: "value", values: ["name", "value", "export"])
  attr(:size, :string, default: "icon")
  attr(:timeout, :any, default: 2000)
  attr(:variant, :string, default: "ghost")
  attr(:id, :string, required: true, doc: "The hook needs one to be found by.")
  attr(:name, :string, required: true, doc: "The variable's name.")
  attr(:value, :string, required: true, doc: "The variable's value.")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction", "disabled"])
  slot(:inner_block)

  def environment_variable_copy_button(assigns) do
    ~H"""
    <LiveShadcn.UI.Button.button
      id={@id}
      phx-hook={LiveBase.Clipboard.hook()}
      phx-mounted={LiveBase.Clipboard.owned_attributes()}
      data-lb-clipboard={
        Map.get(%{"name" => @name, "export" => "export #{@name}=\"#{@value}\""}, @copy_format, @value)
      }
      data-lb-timeout={@timeout}
      size={@size}
      variant={@variant}
      class={["size-6 shrink-0", @class]}
      {@rest}
    >
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon data-lb-state="copied" hidden name="check" width="12" height="12" />
        <LiveShadcn.Icon.icon data-lb-state="idle" name="copy" width="12" height="12" />
      <% end %>
      {render_slot(@inner_block)}
    </LiveShadcn.UI.Button.button>
    """
  end

  @doc "The `environment_variable_required` part."
  attr(:variant, :string, default: "secondary")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def environment_variable_required(assigns) do
    ~H"""
    <LiveShadcn.UI.Badge.badge variant={@variant} class={["text-xs", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        Required
      <% end %>
      {render_slot(@inner_block)}
    </LiveShadcn.UI.Badge.badge>
    """
  end
end
