defmodule LiveAiElements.Components.Image do
  @moduledoc """
  Image.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/image.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `image` part."
  attr(:alt, :string, default: nil)
  attr(:base64, :string, default: nil)
  attr(:media_type, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: [
      "data-slot",
      "src",
      "srcset",
      "sizes",
      "alt",
      "loading",
      "decoding",
      "width",
      "height"
    ]
  )

  def image(assigns) do
    ~H"""
    <img
      alt={@alt}
      src={"data:#{@media_type};base64,#{@base64}"}
      class={["h-auto max-w-full overflow-hidden rounded-md", @class]}
      {@rest}
    />
    """
  end
end
