defmodule LiveAiElements.Components.InlineCitation do
  @moduledoc """
  Inline citation. Built on `shadcn/carousel`.

  Upstream exports 3 more parts, and every one of them is a
  thin wrapper around a part of `<.hover_card>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/inline-citation.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `inline_citation` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def inline_citation(assigns) do
    ~H"""
    <span class={["group inline items-center gap-1", @class]} {@rest}>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `inline_citation_text` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def inline_citation_text(assigns) do
    ~H"""
    <span class={["transition-colors group-hover:bg-accent", @class]} {@rest}>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `inline_citation_carousel` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def inline_citation_carousel(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "carousel"}
      role="region"
      aria-roledescription="carousel"
      class={["relative", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `carousel-content` part."
  attr(:orientation, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def inline_citation_carousel_content(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "carousel-content"}
      class={["overflow-hidden", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <div
        class={["flex", if(@orientation == "horizontal", do: "-ml-4", else: "-mt-4 flex-col"), @class]}
        {@rest}
      />
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `carousel-item` part."
  attr(:orientation, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def inline_citation_carousel_item(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "carousel-item"}
      role="group"
      aria-roledescription="slide"
      class={[
        "min-w-0 shrink-0 grow-0 basis-full w-full space-y-2 p-4 pl-8",
        if(@orientation == "horizontal", do: "pl-4", else: "pt-4"),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `inline_citation_carousel_header` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def inline_citation_carousel_header(assigns) do
    ~H"""
    <div
      class={["flex items-center justify-between gap-2 rounded-t-md bg-secondary p-2", @class]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `inline_citation_carousel_index` part."
  attr(:count, :string, default: "0")
  attr(:current, :string, default: "0")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def inline_citation_carousel_index(assigns) do
    ~H"""
    <div
      class={["flex flex-1 items-center justify-end px-3 py-1 text-muted-foreground text-xs", @class]}
      {@rest}
    >
      <%= if @inner_block == [] do %>
        {"#{@current}/#{@count}"}
      <% end %>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `inline_citation_carousel_prev` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def inline_citation_carousel_prev(assigns) do
    ~H"""
    <button aria-label="Previous" type="button" class={["shrink-0", @class]} {@rest}>
      <LiveShadcn.Icon.icon name="arrow-left" class="size-4 text-muted-foreground" />
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `inline_citation_carousel_next` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def inline_citation_carousel_next(assigns) do
    ~H"""
    <button aria-label="Next" type="button" class={["shrink-0", @class]} {@rest}>
      <LiveShadcn.Icon.icon name="arrow-right" class="size-4 text-muted-foreground" />
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `inline_citation_source` part."
  attr(:description, :string, default: nil)
  attr(:title, :string, default: nil)
  attr(:url, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def inline_citation_source(assigns) do
    ~H"""
    <div class={["space-y-1", @class]} {@rest}>
      <h4 :if={@title} class="truncate font-medium text-sm leading-tight">
        {@title}
      </h4>
      <p :if={@url} class="truncate break-all text-muted-foreground text-xs">
        {@url}
      </p>
      <p :if={@description} class="line-clamp-3 text-muted-foreground text-sm leading-relaxed">
        {@description}
      </p>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `inline_citation_quote` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def inline_citation_quote(assigns) do
    ~H"""
    <blockquote
      class={["border-muted border-l-2 pl-3 text-muted-foreground text-sm italic", @class]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </blockquote>
    """
  end
end
