defmodule LiveAiElements.Components.JsxPreview do
  @moduledoc """
  Jsx preview.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/jsx-preview.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `jsx_preview` part."
  attr(:bindings, :string, default: nil)
  attr(:components, :string, default: nil)
  attr(:is_streaming, :boolean, default: false)
  attr(:jsx, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def jsx_preview(assigns) do
    ~H"""
    <div class={["relative", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `jsx_preview_content` part."
  attr(:bindings, :string, default: nil)
  attr(:components, :string, default: nil)
  attr(:display_jsx, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def jsx_preview_content(assigns) do
    ~H"""
    <div class={["jsx-preview-content", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `jsx_preview_error` part."
  attr(:error, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def jsx_preview_error(assigns) do
    ~H"""
    <div
      :if={@error}
      class={[
        "flex items-center gap-2 rounded-md border border-destructive/50 bg-destructive/10 p-3 text-destructive text-sm",
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
      <LiveShadcn.Icon.icon :if={!@children} name="circle-alert" class="size-4 shrink-0" /><span :if={
        !@children
      }>{@error.message}</span>
      {render_slot(@inner_block)}
    </div>
    """
  end
end
