defmodule LiveAiElements.Components.MicSelector do
  @moduledoc """
  Mic selector. Built on `shadcn/button`, `shadcn/command`, `shadcn/input-group`, `shadcn/popover`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/mic-selector.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.
  """

  use Phoenix.Component

  alias LiveBase.FormControl
  alias LiveBase.Listbox
  alias LiveBase.Popover

  @doc """
  Built on `shadcn/button`, `shadcn/command`, `shadcn/input-group`, `shadcn/popover`.

      <.mic_selector id="style" field={@form[:style]}>
        <:option value="vega" label="Vega" />
        <:option value="nova" label="Nova" />
      </.mic_selector>

  The trigger is a button, and a button submits nothing, so there is a hidden
  input beside it carrying the chosen value. Choosing runs on the client and
  fires `change`, so `phx-change` still sees it.
  """
  attr(:id, :string, required: true, doc: "Every id inside the listbox derives from it.")

  attr(:field, Phoenix.HTML.FormField,
    default: nil,
    doc: "A form field. Fills in id, name, value and errors."
  )

  attr(:name, :string, default: nil)
  attr(:value, :any, default: nil, doc: "The chosen value.")

  attr(:placeholder, :string,
    default: "Select…",
    doc: "What the trigger reads with nothing chosen."
  )

  attr(:labelledby, :string, default: nil, doc: "The id of the label that names it.")
  attr(:errors, :list, default: [])
  attr(:open, :boolean, default: false)
  attr(:disabled, :boolean, default: false)
  attr(:readonly, :boolean, default: false)
  attr(:required, :boolean, default: false)
  attr(:side, :string, default: "bottom", values: ["top", "right", "bottom", "left"])
  attr(:align, :string, default: "start", values: ["start", "center", "end"])
  attr(:offset, :integer, default: 4)
  attr(:class, :any, default: nil, doc: "Appended to the list's class string.")
  attr(:list_class, :any, default: nil)
  attr(:item_class, :any, default: nil)
  attr(:trigger_class, :any, default: nil)
  attr(:align_offset, :string, default: "0")
  attr(:data, :string, default: nil)
  attr(:default_open, :boolean, default: false)
  attr(:default_value, :string, default: nil)
  attr(:popover_options, :string, default: nil)
  attr(:side_offset, :string, default: "4")

  attr(:size, :string,
    default: "default",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:variant, :string,
    default: "outline",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:width, :any, default: nil)
  attr(:rest, :global)

  slot :option, doc: "One value to choose." do
    attr(:value, :string, required: true, doc: "Unique. What the form submits.")
    attr(:label, :string, doc: "What it reads. Defaults to the value.")
    attr(:disabled, :boolean)
  end

  slot(:inner_block, doc: "Anything the options do not cover.")

  def mic_selector(assigns) do
    assigns = FormControl.from_field(assigns)

    ~H"""
    <div
      id={@id}
      phx-window-keydown={Popover.close(@id)}
      phx-key="Escape"
      phx-click-away={Popover.dismiss(@id)}
      {@rest}
    >
      <button
        data-slot="popover-trigger"
        id={Popover.trigger_id(@id)}
        type="button"
        role="combobox"
        aria-labelledby={@labelledby}
        aria-haspopup="listbox"
        aria-expanded={to_string(@open)}
        aria-controls={Popover.popup_id(@id)}
        phx-click={if(not @disabled, do: Popover.toggle(@id))}
        phx-mounted={Popover.owned_attributes(:trigger)}
        data-popup-open={flag(@open)}
        data-pressed={flag(@open)}
        aria-invalid={to_string(@errors != [])}
        class={[
          variant_class("buttonVariants", "size", @size),
          variant_class("buttonVariants", "variant", @variant),
          "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
          @trigger_class
        ]}
      >
        {label(@option, @value) || @placeholder}
        <LiveShadcn.Icon.icon
          name="chevrons-up-down"
          width="16"
          height="16"
          class="shrink-0 text-muted-foreground"
        />
      </button>
      <input
        type="hidden"
        id={Listbox.input_id(@id)}
        name={@name}
        value={@value}
        disabled={@disabled}
        required={@required}
        phx-mounted={Listbox.owned_attributes(:input)}
      />
      <div class={["p-0", @class]}>
        <div
          id={Popover.positioner_id(@id)}
          hidden={not @open}
          phx-hook={Popover.hook()}
          data-lb-anchor={Popover.trigger_id(@id)}
          data-lb-side={@side}
          data-lb-align={@align}
          data-lb-offset={to_string(@offset)}
          data-lb-autofocus
          phx-mounted={Popover.owned_attributes(:positioner)}
          data-open={flag(@open)}
          data-closed={flag(not @open)}
          class="isolate z-50"
        >
          <div
            data-slot="popover-content"
            id={Popover.popup_id(@id)}
            role="listbox"
            tabindex="-1"
            hidden={not @open}
            data-lb-popup
            phx-hook="LiveBase.Roving"
            data-lb-roving="option"
            data-lb-orientation="vertical"
            data-lb-highlight="data-highlighted"
            phx-mounted={Popover.owned_attributes(:popup)}
            data-open={flag(@open)}
            data-closed={flag(not @open)}
            class={[
              "cn-popover-content cn-popover-content-logical z-50 w-72 origin-(--transform-origin) outline-hidden",
              @class
            ]}
            data-lb-style-target
            data-lb-measure
          >
            <div
              :for={option <- @option}
              data-slot="command-item"
              id={Listbox.option_id(@id, option[:value])}
              role="option"
              tabindex="-1"
              aria-selected={to_string(option[:value] == @value)}
              data-selected={flag(option[:value] == @value)}
              phx-click={
                if(option[:disabled] != true,
                  do: Listbox.choose(listbox: @id, value: option[:value], label: option[:label])
                )
              }
              phx-mounted={Listbox.owned_attributes(:option)}
              data-disabled={flag(option[:disabled] == true)}
              class={[
                "cn-command-item group/command-item data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
                @item_class
              ]}
              data-lb-style-target
            >
              <LiveShadcn.Icon.icon
                name="check"
                class="cn-command-item-indicator ml-auto opacity-0 group-has-data-[slot=command-shortcut]/command-item:hidden group-data-[checked=true]/command-item:opacity-100"
              />
              {option[:label] || option[:value]}
            </div>
          </div>
        </div>
        <div
          data-slot="command"
          value={@value}
          class="cn-command flex size-full flex-col overflow-hidden"
        />
      </div>
    </div>
    """
  end

  # What the trigger reads before anything has been chosen, and after.
  defp label(options, value) do
    case Enum.find(options, &(&1[:value] == value)) do
      nil -> nil
      option -> option[:label] || option[:value]
    end
  end

  defp flag(true), do: ""
  defp flag(_state), do: nil

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "size" => %{
        "default" => "cn-button-size-default",
        "icon" => "cn-button-size-icon",
        "icon-lg" => "cn-button-size-icon-lg",
        "icon-sm" => "cn-button-size-icon-sm",
        "icon-xs" => "cn-button-size-icon-xs",
        "lg" => "cn-button-size-lg",
        "sm" => "cn-button-size-sm",
        "xs" => "cn-button-size-xs"
      },
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
