defmodule LiveAiElements.Components.OpenInChat do
  @moduledoc """
  Open in chat. Built on `shadcn/dropdown-menu`.

  Upstream exports 11 more parts, and every one of them is a
  thin wrapper around a part of `<.dropdown_menu>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/open-in-chat.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `open_in` part."
  attr(:query, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def open_in(assigns) do
    ~H"""
    {render_slot(@inner_block)}
    """
  end
end
