defmodule LiveAiElements.Components.PackageInfo do
  @moduledoc """
  Package info. Built on `shadcn/badge`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/package-info.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `package_info_header` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def package_info_header(assigns) do
    ~H"""
    <div class={["flex items-center justify-between gap-2", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `package_info_name` part."
  attr(:name, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def package_info_name(assigns) do
    ~H"""
    <div class={["flex items-center gap-2", @class]} {@rest}>
      <LiveShadcn.Icon.icon name="package" class="size-4 text-muted-foreground" />
      <span class="font-medium font-mono text-sm">
        {render_slot(@inner_block)}
      </span>
    </div>
    """
  end

  @doc "The `badge` part."
  attr(:change_type, :string, default: nil)

  attr(:variant, :string,
    default: "default",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def package_info_change_type(assigns) do
    ~H"""
    <span
      data-slot={@rest[:"data-slot"] || "badge"}
      class={[
        "cn-badge group/badge inline-flex w-fit shrink-0 items-center justify-center overflow-hidden whitespace-nowrap focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none gap-1 text-xs capitalize",
        variant_class("variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <LiveShadcn.Icon.icon :if={@change_type == "added"} name="plus" class="size-3" />
      <LiveShadcn.Icon.icon :if={@change_type == "major"} name="arrow-right" class="size-3" />
      <LiveShadcn.Icon.icon :if={@change_type == "minor"} name="arrow-right" class="size-3" />
      <LiveShadcn.Icon.icon :if={@change_type == "patch"} name="arrow-right" class="size-3" />
      <LiveShadcn.Icon.icon :if={@change_type == "removed"} name="minus" class="size-3" />
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `package_info_version` part."
  attr(:current_version, :string, default: nil)
  attr(:new_version, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def package_info_version(assigns) do
    ~H"""
    <div
      class={["mt-2 flex items-center gap-2 font-mono text-muted-foreground text-sm", @class]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `package_info` part."
  attr(:change_type, :string, default: nil)
  attr(:context_value, :string, default: nil)
  attr(:current_version, :string, default: nil)
  attr(:name, :string, default: nil)
  attr(:new_version, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def package_info(assigns) do
    ~H"""
    <div class={["rounded-lg border bg-background p-4", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `package_info_description` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def package_info_description(assigns) do
    ~H"""
    <p class={["mt-2 text-muted-foreground text-sm", @class]} {@rest}>
      {render_slot(@inner_block)}
    </p>
    """
  end

  @doc "The `package_info_content` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def package_info_content(assigns) do
    ~H"""
    <div class={["mt-3 border-t pt-3", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `package_info_dependencies` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def package_info_dependencies(assigns) do
    ~H"""
    <div class={["space-y-2", @class]} {@rest}>
      <span class="font-medium text-muted-foreground text-xs uppercase tracking-wide">
        Dependencies
      </span>
      <div class="space-y-1">
        {render_slot(@inner_block)}
      </div>
    </div>
    """
  end

  @doc "The `package_info_dependency` part."
  attr(:name, :string, default: nil)
  attr(:version, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def package_info_dependency(assigns) do
    ~H"""
    <div class={["flex items-center justify-between text-sm", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  # The variant table, from the `cva` call upstream writes it in.
  @variants %{
    "variant" => %{
      "default" => "cn-badge-variant-default",
      "destructive" => "cn-badge-variant-destructive",
      "ghost" => "cn-badge-variant-ghost",
      "link" => "cn-badge-variant-link",
      "outline" => "cn-badge-variant-outline",
      "secondary" => "cn-badge-variant-secondary"
    }
  }

  defp variant_class(group, value), do: get_in(@variants, [group, value])
end
