defmodule LiveAiElements.Components.Panel do
  @moduledoc """
  Panel.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/panel.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `panel` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def panel(assigns) do
    ~H"""
    <div class={["m-4 overflow-hidden rounded-md border bg-card p-1", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end
end
