defmodule LiveAiElements.Components.Plan do
  @moduledoc """
  Plan. Built on `shadcn/button`, `shadcn/card`, `shadcn/collapsible`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/plan.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.

  | Upstream | Digest |
  |---|---|
  | `ai_elements/plan.tsx` | `bfa20e90199f` |
  """

  use Phoenix.Component

  alias LiveBase.Disclosure

  @doc """
  Built on `shadcn/button`, `shadcn/card`, `shadcn/collapsible`.

      <.plan id="details" title="Show details">
        The panel body.
      </.plan>

  Opening and closing runs entirely on the client. The server is not told,
  and does not need to be: the state is whether a reader is looking at it.
  """
  attr(:id, :string, required: true, doc: "Every id inside the component derives from it.")
  attr(:title, :any, required: true, doc: "The trigger content.")

  attr(:open, :boolean,
    default: false,
    doc:
      "Whether the collapsible panel is initially open. To render a controlled collapsible, use the `open` prop instead."
  )

  attr(:disabled, :boolean,
    default: false,
    doc: "Whether the component should ignore user interaction."
  )

  attr(:orientation, :string, default: "vertical", doc: "")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:content_class, :any, default: nil, doc: "Appended to the content class string.")
  attr(:trigger_class, :any, default: nil, doc: "Appended to the trigger class string.")
  attr(:rest, :global)

  slot(:inner_block, required: true, doc: "The panel body.")
  attr(:size, :any, default: nil)

  def plan(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "plan"}
      id={@id}
      data-open={flag(@open)}
      data-closed={flag(not @open)}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <div
        data-slot={@rest[:"data-slot"] || "card"}
        data-size={@size}
        class={["cn-card group/card flex flex-col shadow-none", @class]}
        {Map.drop(@rest, [:"data-slot"])}
      >
        <button
          data-slot="collapsible-trigger"
          id={Disclosure.trigger_id(@id)}
          type="button"
          aria-expanded={to_string(@open)}
          aria-controls={Disclosure.panel_id(@id)}
          phx-click={interactive(@disabled, Disclosure.toggle(item: @id, root: @id, multiple: true))}
          phx-mounted={Disclosure.owned_attributes(:trigger)}
          data-panel-open={flag(@open)}
        >
          <button data-slot="plan-trigger" class={["size-8", @trigger_class]}>
            <LiveShadcn.Icon.icon name="chevrons-up-down" class="size-4" />
            <span class="sr-only">
              Toggle plan
            </span>
          </button>
          {@title}
        </button>
        <div
          data-slot="collapsible-content"
          id={Disclosure.panel_id(@id)}
          role="region"
          aria-labelledby={Disclosure.trigger_id(@id)}
          hidden={not @open}
          phx-hook={Disclosure.hook()}
          phx-mounted={Disclosure.owned_attributes(:panel)}
          data-lb-height-var="--collapsible-panel-height"
          data-lb-width-var="--collapsible-panel-width"
          data-open={flag(@open)}
          data-closed={flag(not @open)}
        >
          <div data-slot="plan-content" class={["cn-card-content", @content_class]} />
          {render_slot(@inner_block)}
        </div>
      </div>
    </div>
    """
  end

  # A disabled disclosure ignores interaction. `aria-disabled` and
  # `pointer-events-none` say so to a reader and to a mouse, but a keypress
  # on a focused trigger reaches neither, so the command itself is withheld.
  defp interactive(false, command), do: command
  defp interactive(_disabled, _command), do: nil

  # An HTML attribute with no value, or no attribute at all. Base UI marks
  # state by presence, so `data-open=""` and a missing `data-open` are the
  # two states a shadcn class string distinguishes.
  defp flag(true), do: ""
  defp flag(_state), do: nil
end
