defmodule LiveAiElements.Components.Question do
  @moduledoc """
  Question. Built on `shadcn/button`, `shadcn/textarea`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/question.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `question` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: ["data-slot", "action", "method", "enctype", "novalidate", "target"]
  )

  slot(:inner_block)

  def question(assigns) do
    ~H"""
    <form class={["space-y-4 rounded-lg border bg-background p-4", @class]} {@rest}>
      {render_slot(@inner_block)}
    </form>
    """
  end

  @doc "The `question_prompt` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def question_prompt(assigns) do
    ~H"""
    <p class={["font-medium text-sm", @class]} {@rest}>
      {render_slot(@inner_block)}
    </p>
    """
  end

  @doc "The `question_description` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def question_description(assigns) do
    ~H"""
    <p class={["text-muted-foreground text-sm", @class]} {@rest}>
      {render_slot(@inner_block)}
    </p>
    """
  end

  @doc "The `question_options` part."
  attr(:selection_mode, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def question_options(assigns) do
    ~H"""
    <div
      role={if(@selection_mode == "single", do: "radiogroup", else: "group")}
      class={["flex flex-wrap gap-2", @class]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `button` part."
  attr(:disabled, :string, default: nil)
  attr(:is_selected, :string, default: nil)
  attr(:role, :string, default: nil)
  attr(:size, :string, default: "default")
  attr(:value, :string, default: nil)

  attr(:variant, :string,
    default: "default",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def question_option(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "button"}
      aria-checked={@is_selected}
      disabled={@disabled}
      role={@role}
      type="button"
      class={[
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 cn-button-size-default h-auto whitespace-normal",
        variant_class("buttonVariants", "variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        {@value}
      <% end %>
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `textarea` part."
  attr(:disabled, :string, default: nil)
  attr(:text, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: ["data-slot", "name", "placeholder", "rows", "cols", "readonly", "wrap"]
  )

  slot(:inner_block)

  def question_input(assigns) do
    ~H"""
    <textarea
      data-slot={@rest[:"data-slot"] || "textarea"}
      disabled={@disabled}
      class={[
        "cn-textarea flex field-sizing-content min-h-16 w-full outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50 min-h-20",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >{@text}{render_slot(@inner_block)}</textarea>
    """
  end

  @doc "The `question_actions` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def question_actions(assigns) do
    ~H"""
    <div class={["flex items-center justify-end gap-2", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `button` part."
  attr(:disabled, :string, default: nil)
  attr(:has_response, :string, default: nil)
  attr(:size, :string, default: "default")
  attr(:variant, :string, default: "default")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def question_submit(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "button"}
      disabled={@disabled || @disabled || !@has_response}
      type="submit"
      class={[
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 cn-button-size-default cn-button-variant-default",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
