defmodule LiveAiElements.Components.Queue do
  @moduledoc """
  Queue. Built on `shadcn/button`, `shadcn/scroll-area`.

  Upstream exports 3 more parts, and every one of them is a
  thin wrapper around a part of `<.collapsible>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/queue.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `queue_item` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def queue_item(assigns) do
    ~H"""
    <li
      class={[
        "group flex flex-col gap-1 rounded-md px-3 py-1 text-sm transition-colors hover:bg-muted",
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </li>
    """
  end

  @doc "The `queue_item_indicator` part."
  attr(:completed, :boolean, default: false)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def queue_item_indicator(assigns) do
    ~H"""
    <span
      class={[
        "mt-0.5 inline-block size-2.5 rounded-full border",
        if(@completed,
          do: "border-muted-foreground/20 bg-muted-foreground/10",
          else: "border-muted-foreground/50"
        ),
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `queue_item_content` part."
  attr(:completed, :boolean, default: false)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def queue_item_content(assigns) do
    ~H"""
    <span
      class={[
        "line-clamp-1 grow break-words",
        if(@completed, do: "text-muted-foreground/50 line-through", else: "text-muted-foreground"),
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `queue_item_description` part."
  attr(:completed, :boolean, default: false)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def queue_item_description(assigns) do
    ~H"""
    <div
      class={[
        "ml-6 text-xs",
        if(@completed, do: "text-muted-foreground/40 line-through", else: "text-muted-foreground"),
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `queue_item_actions` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def queue_item_actions(assigns) do
    ~H"""
    <div class={["flex gap-1", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `button` part."
  attr(:size, :string,
    default: "icon",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:variant, :string,
    default: "ghost",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def queue_item_action(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "button"}
      type="button"
      class={[
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 size-auto rounded p-1 text-muted-foreground opacity-0 transition-opacity hover:bg-muted-foreground/10 hover:text-foreground group-hover:opacity-100",
        variant_class("buttonVariants", "size", @size),
        variant_class("buttonVariants", "variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `queue_item_attachment` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def queue_item_attachment(assigns) do
    ~H"""
    <div class={["mt-1 flex flex-wrap gap-2", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `queue_item_image` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: [
      "data-slot",
      "src",
      "srcset",
      "sizes",
      "alt",
      "loading",
      "decoding",
      "width",
      "height"
    ]
  )

  def queue_item_image(assigns) do
    ~H"""
    <img
      alt=""
      height={32}
      width={32}
      class={["h-8 w-8 rounded border object-cover", @class]}
      {@rest}
    />
    """
  end

  @doc "The `queue_item_file` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def queue_item_file(assigns) do
    ~H"""
    <span
      class={["flex items-center gap-1 rounded border bg-muted px-2 py-1 text-xs", @class]}
      {@rest}
    >
      <LiveShadcn.Icon.icon name="paperclip" width="12" height="12" />
      <span class="max-w-[100px] truncate">
        {render_slot(@inner_block)}
      </span>
    </span>
    """
  end

  @doc "The `scroll-area` part."
  attr(:orientation, :string, default: "vertical")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def queue_list(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "scroll-area"}
      class={["cn-scroll-area relative mt-2 -mb-1", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <div
        data-slot="scroll-area-viewport"
        class="cn-scroll-area-viewport size-full rounded-[inherit] transition-[color,box-shadow] outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50 focus-visible:outline-1"
      >
        <div class="max-h-40 pr-4">
          <ul>
            {render_slot(@inner_block)}
          </ul>
        </div>
      </div>
      <div
        data-slot={@rest[:"data-slot"] || "scroll-area-scrollbar"}
        data-orientation={@orientation}
        orientation={@orientation}
        class={["cn-scroll-area-scrollbar flex touch-none p-px transition-colors select-none", @class]}
        {Map.drop(@rest, [:"data-slot"])}
      >
        <div data-slot="scroll-area-thumb" class="cn-scroll-area-thumb relative flex-1 bg-border" />
      </div>
      <div />
    </div>
    """
  end

  @doc "The `queue_section_label` part."
  attr(:count, :any, default: nil)
  attr(:icon, :string, default: nil)
  attr(:label, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def queue_section_label(assigns) do
    ~H"""
    <span class={["flex items-center gap-2", @class]} {@rest}>
      <LiveShadcn.Icon.icon
        name="chevron-down"
        class="size-4 transition-transform group-data-[state=closed]:-rotate-90"
      />
      {@icon}
      <span>
        {@count}
        {@label}
      </span>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `queue` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def queue(assigns) do
    ~H"""
    <div
      class={[
        "flex flex-col gap-2 rounded-xl border border-border bg-background px-3 pt-2 pb-2 shadow-xs",
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "size" => %{
        "default" => "cn-button-size-default",
        "icon" => "cn-button-size-icon",
        "icon-lg" => "cn-button-size-icon-lg",
        "icon-sm" => "cn-button-size-icon-sm",
        "icon-xs" => "cn-button-size-icon-xs",
        "lg" => "cn-button-size-lg",
        "sm" => "cn-button-size-sm",
        "xs" => "cn-button-size-xs"
      },
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
