defmodule LiveAiElements.Components.Snippet do
  @moduledoc """
  Snippet. Built on `shadcn/button`, `shadcn/input`, `shadcn/input-group`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/snippet.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `snippet` part."
  attr(:code, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def snippet(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "input-group"}
      role="group"
      class={[
        "group/input-group cn-input-group relative flex w-full min-w-0 items-center outline-none has-[>textarea]:h-auto font-mono",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `input-group-addon` part."
  attr(:align, :string,
    default: "inline-start",
    values: ["block-end", "block-start", "inline-end", "inline-start"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def snippet_addon(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "input-group-addon"}
      role="group"
      data-align={@align}
      class={[
        variant_class("inputGroupAddonVariants", "align", @align),
        "cn-input-group-addon flex cursor-text items-center justify-center select-none",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `snippet_text` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def snippet_text(assigns) do
    ~H"""
    <span
      class={[
        "cn-input-group-text flex items-center [&_svg]:pointer-events-none pl-2 font-normal text-muted-foreground",
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `input-group-control` part."
  attr(:code, :string, default: nil)
  attr(:type, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: [
      "data-slot",
      "type",
      "name",
      "value",
      "placeholder",
      "checked",
      "min",
      "max",
      "step",
      "minlength",
      "maxlength",
      "pattern",
      "readonly",
      "multiple",
      "autocomplete"
    ]
  )

  def snippet_input(assigns) do
    ~H"""
    <input
      data-slot={@rest[:"data-slot"] || "input-group-control"}
      type={@type}
      readonly
      value={@code}
      class={[
        "cn-input w-full min-w-0 outline-none file:inline-flex file:border-0 file:bg-transparent file:text-foreground placeholder:text-muted-foreground disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 cn-input-group-input flex-1 text-foreground",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    />
    """
  end

  @doc "The `button` part."
  attr(:size, :string, default: "icon-sm", values: ["icon-sm", "icon-xs", "sm", "xs"])
  attr(:timeout, :any, default: 2000)
  attr(:type, :string, default: "button")

  attr(:variant, :string,
    default: "ghost",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:id, :string, required: true, doc: "The hook needs one to be found by.")
  attr(:code, :string, required: true, doc: "The text the button copies.")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def snippet_copy_button(assigns) do
    ~H"""
    <button
      id={@id}
      phx-hook={LiveBase.Clipboard.hook()}
      phx-mounted={LiveBase.Clipboard.owned_attributes()}
      data-lb-clipboard={@code}
      data-lb-timeout={@timeout}
      data-slot={@rest[:"data-slot"] || "button"}
      type={@type}
      data-size={@size}
      aria-label="Copy"
      title="Copy"
      class={[
        variant_class("buttonVariants", "variant", @variant),
        variant_class("inputGroupButtonVariants", "size", @size),
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 cn-button-size-default cn-input-group-button flex items-center shadow-none",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon
          data-lb-state="copied"
          hidden
          name="check"
          width="14"
          height="14"
          class="size-3.5"
        />
        <LiveShadcn.Icon.icon
          data-lb-state="idle"
          name="copy"
          width="14"
          height="14"
          class="size-3.5"
        />
      <% end %>
      {render_slot(@inner_block)}
    </button>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    },
    "inputGroupAddonVariants" => %{
      "align" => %{
        "block-end" => "cn-input-group-addon-align-block-end order-last w-full justify-start",
        "block-start" =>
          "cn-input-group-addon-align-block-start order-first w-full justify-start",
        "inline-end" => "cn-input-group-addon-align-inline-end order-last",
        "inline-start" => "cn-input-group-addon-align-inline-start order-first"
      }
    },
    "inputGroupButtonVariants" => %{
      "size" => %{
        "icon-sm" => "cn-input-group-button-size-icon-sm",
        "icon-xs" => "cn-input-group-button-size-icon-xs",
        "sm" => "cn-input-group-button-size-sm",
        "xs" => "cn-input-group-button-size-xs"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
