defmodule LiveAiElements.Components.SpeechInput do
  @moduledoc """
  Speech input. Built on `shadcn/button`, `shadcn/spinner`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/speech-input.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `speech_input` part."
  attr(:is_disabled, :string, default: nil)
  attr(:is_listening, :boolean, default: false)
  attr(:is_processing, :boolean, default: false)
  attr(:lang, :string, default: "en-US")

  attr(:size, :string,
    default: "default",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:variant, :string,
    default: "default",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def speech_input(assigns) do
    ~H"""
    <div class="relative inline-flex items-center justify-center">
      <div
        :for={index <- [0, 1, 2]}
        :if={@is_listening}
        style={"animation-delay: #{"#{index * 0.3}s"}; animation-duration: 2s"}
        class="absolute inset-0 animate-ping rounded-full border-2 border-red-400/30"
      />
      <button
        data-slot={@rest[:"data-slot"] || "button"}
        disabled={@is_disabled}
        class={[
          "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 relative z-10 rounded-full transition-all duration-300",
          if(@is_listening,
            do: "bg-destructive text-white hover:bg-destructive/80 hover:text-white",
            else:
              "bg-primary text-primary-foreground hover:bg-primary/80 hover:text-primary-foreground"
          ),
          variant_class("buttonVariants", "size", @size),
          variant_class("buttonVariants", "variant", @variant),
          @class
        ]}
        {Map.drop(@rest, [:"data-slot"])}
      >
        <LiveShadcn.Icon.icon
          :if={@is_processing}
          name="loader-2"
          data-slot={@rest[:"data-slot"] || "spinner"}
          class="size-4 animate-spin"
          {Map.drop(@rest, [:"data-slot"])}
        />
        <LiveShadcn.Icon.icon :if={!@is_processing && @is_listening} name="square" class="size-4" />
        <LiveShadcn.Icon.icon :if={!@is_processing || @is_listening} name="mic" class="size-4" />
        {render_slot(@inner_block)}
      </button>
    </div>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "size" => %{
        "default" => "cn-button-size-default",
        "icon" => "cn-button-size-icon",
        "icon-lg" => "cn-button-size-icon-lg",
        "icon-sm" => "cn-button-size-icon-sm",
        "icon-xs" => "cn-button-size-icon-xs",
        "lg" => "cn-button-size-lg",
        "sm" => "cn-button-size-sm",
        "xs" => "cn-button-size-xs"
      },
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
