defmodule LiveAiElements.Components.StackTrace do
  @moduledoc """
  Stack trace. Built on `shadcn/button`.

  Upstream exports 2 more parts, and every one of them is a
  thin wrapper around a part of `<.collapsible>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/stack-trace.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `stack_trace` part."
  attr(:default_open, :boolean, default: false)
  attr(:open, :boolean, default: nil)
  attr(:trace, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def stack_trace(assigns) do
    ~H"""
    <div
      class={[
        "not-prose w-full overflow-hidden rounded-lg border bg-background font-mono text-sm",
        @class
      ]}
      {@rest}
    >
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `stack_trace_error` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def stack_trace_error(assigns) do
    ~H"""
    <div class={["flex flex-1 items-center gap-2 overflow-hidden", @class]} {@rest}>
      <LiveShadcn.Icon.icon name="triangle-alert" class="size-4 shrink-0 text-destructive" />
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `stack_trace_error_type` part."
  attr(:trace, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def stack_trace_error_type(assigns) do
    ~H"""
    <span class={["shrink-0 font-semibold text-destructive", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        {@trace.errorType}
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `stack_trace_error_message` part."
  attr(:trace, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def stack_trace_error_message(assigns) do
    ~H"""
    <span class={["truncate text-foreground", @class]} {@rest}>
      <%= if @inner_block == [] do %>
        {@trace.errorMessage}
      <% end %>
      {render_slot(@inner_block)}
    </span>
    """
  end

  @doc "The `stack_trace_actions` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def stack_trace_actions(assigns) do
    ~H"""
    <div role="group" class={["flex shrink-0 items-center gap-1", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `button` part."
  attr(:size, :string,
    default: "icon",
    values: ["default", "icon", "icon-lg", "icon-sm", "icon-xs", "lg", "sm", "xs"]
  )

  attr(:timeout, :any, default: "2000")

  attr(:variant, :string,
    default: "ghost",
    values: ["default", "destructive", "ghost", "link", "outline", "secondary"]
  )

  attr(:id, :string, required: true, doc: "The hook needs one to be found by.")
  attr(:raw, :string, required: true, doc: "The stack trace the button copies.")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def stack_trace_copy_button(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "button"}
      id={@id}
      phx-hook={LiveBase.Clipboard.hook()}
      phx-mounted={LiveBase.Clipboard.owned_attributes()}
      data-lb-clipboard={@raw}
      data-lb-timeout={@timeout}
      class={[
        "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 size-7",
        variant_class("buttonVariants", "size", @size),
        variant_class("buttonVariants", "variant", @variant),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <%= if @inner_block == [] do %>
        <LiveShadcn.Icon.icon data-lb-state="copied" hidden name="check" width="14" height="14" />
        <LiveShadcn.Icon.icon data-lb-state="idle" name="copy" width="14" height="14" />
      <% end %>
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc "The `stack_trace_expand_button` part."
  attr(:is_open, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def stack_trace_expand_button(assigns) do
    ~H"""
    <div class={["flex size-7 items-center justify-center", @class]} {@rest}>
      <LiveShadcn.Icon.icon
        name="chevron-down"
        class={[
          "size-4 text-muted-foreground transition-transform",
          if(@is_open, do: "rotate-180", else: "rotate-0")
        ]}
      />
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `stack_trace_frames` part."
  attr(:frames_to_show, :any, default: nil)
  attr(:show_internal_frames, :boolean, default: true)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def stack_trace_frames(assigns) do
    ~H"""
    <div class={["space-y-1 p-3", @class]} {@rest}>
      <div
        :for={frame <- @frames_to_show}
        class={[
          "text-xs",
          if(frame.isInternal, do: "text-muted-foreground/50", else: "text-foreground/90")
        ]}
      >
        <span class="text-muted-foreground">
          at
        </span>
        <span :if={frame.functionName}>
          {frame.functionName}
        </span>
        <span :if={frame.filePath} class="text-muted-foreground">
          (
        </span>
        <button
          :if={frame.filePath}
          disabled={!true}
          type="button"
          class={["underline decoration-dotted hover:text-primary", "cursor-pointer"]}
        >
          {frame.filePath}
          {frame.lineNumber != nil && ":#{frame.lineNumber}"}
          {frame.columnNumber != nil && ":#{frame.columnNumber}"}
        </button>
        <span :if={frame.filePath} class="text-muted-foreground">
          )
        </span>
        <span :if={!frame.filePath || frame.functionName}>
          {String.replace(frame.raw, ~r/^at\s+/, "", global: false)}
        </span>
      </div>
      <div :if={length(@frames_to_show) == 0} class="text-muted-foreground text-xs">
        No stack frames
      </div>
      {render_slot(@inner_block)}
    </div>
    """
  end

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "buttonVariants" => %{
      "size" => %{
        "default" => "cn-button-size-default",
        "icon" => "cn-button-size-icon",
        "icon-lg" => "cn-button-size-icon-lg",
        "icon-sm" => "cn-button-size-icon-sm",
        "icon-xs" => "cn-button-size-icon-xs",
        "lg" => "cn-button-size-lg",
        "sm" => "cn-button-size-sm",
        "xs" => "cn-button-size-xs"
      },
      "variant" => %{
        "default" => "cn-button-variant-default",
        "destructive" => "cn-button-variant-destructive",
        "ghost" => "cn-button-variant-ghost",
        "link" => "cn-button-variant-link",
        "outline" => "cn-button-variant-outline",
        "secondary" => "cn-button-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
