defmodule LiveAiElements.Components.Toolbar do
  @moduledoc """
  Toolbar.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/toolbar.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `toolbar` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def toolbar(assigns) do
    ~H"""
    <div class={["flex items-center gap-1 rounded-sm border bg-background p-1.5", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end
end
