defmodule LiveAiElements.Components.Tool do
  @moduledoc """
  Tool. Built on `shadcn/badge`, `shadcn/collapsible`.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/tool.json`. Every
  class string, every `data-slot`, and every data attribute below came from
  upstream. Change the spec or the recipe, not this file.

  | Upstream | Digest |
  |---|---|
  | `ai_elements/tool.tsx` | `5b520e0c3379` |
  """

  use Phoenix.Component

  alias LiveBase.Disclosure

  @doc """
  Built on `shadcn/badge`, `shadcn/collapsible`.

      <.tool id="details" title="Show details">
        The panel body.
      </.tool>

  Opening and closing runs entirely on the client. The server is not told,
  and does not need to be: the state is whether a reader is looking at it.
  """
  attr(:id, :string, required: true, doc: "Every id inside the component derives from it.")
  attr(:title, :any, required: true, doc: "The trigger content.")

  attr(:open, :boolean,
    default: false,
    doc:
      "Whether the collapsible panel is initially open. To render a controlled collapsible, use the `open` prop instead."
  )

  attr(:disabled, :boolean,
    default: false,
    doc: "Whether the component should ignore user interaction."
  )

  attr(:orientation, :string, default: "vertical", doc: "")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:content_class, :any, default: nil, doc: "Appended to the content class string.")
  attr(:header_class, :any, default: nil, doc: "Appended to the header class string.")
  attr(:rest, :global)

  slot(:inner_block, required: true, doc: "The panel body.")
  attr(:derived_name, :any, default: nil)
  attr(:state, :any, default: nil)
  attr(:variant, :any, default: nil)

  def tool(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "collapsible"}
      id={@id}
      data-open={flag(@open)}
      data-closed={flag(not @open)}
      class={["group not-prose mb-4 w-full rounded-md border", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      <button
        data-slot="collapsible-trigger"
        id={Disclosure.trigger_id(@id)}
        type="button"
        aria-expanded={to_string(@open)}
        aria-controls={Disclosure.panel_id(@id)}
        phx-click={interactive(@disabled, Disclosure.toggle(item: @id, root: @id, multiple: true))}
        phx-mounted={Disclosure.owned_attributes(:trigger)}
        data-panel-open={flag(@open)}
        class={["flex w-full items-center justify-between gap-4 p-3", @header_class]}
      >
        <div class="flex items-center gap-2">
          <LiveShadcn.Icon.icon name="wrench" class="size-4 text-muted-foreground" />
          <span class="font-medium text-sm">
            {@title || @derived_name}
          </span>
          <span
            data-slot="badge"
            data-variant={@variant}
            class={[
              "cn-badge group/badge inline-flex w-fit shrink-0 items-center justify-center overflow-hidden whitespace-nowrap focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none gap-1.5 rounded-full text-xs",
              variant_class("badgeVariants", "variant", @variant)
            ]}
          >
            <LiveShadcn.Icon.icon
              :if={@state == "approval-requested"}
              name="clock"
              class="size-4 text-yellow-600"
            />
            <LiveShadcn.Icon.icon
              :if={@state == "approval-responded"}
              name="circle-check-big"
              class="size-4 text-blue-600"
            />
            <LiveShadcn.Icon.icon
              :if={@state == "input-available"}
              name="clock"
              class="size-4 animate-pulse"
            />
            <LiveShadcn.Icon.icon :if={@state == "input-streaming"} name="circle" class="size-4" />
            <LiveShadcn.Icon.icon
              :if={@state == "output-available"}
              name="circle-check-big"
              class="size-4 text-green-600"
            />
            <LiveShadcn.Icon.icon
              :if={@state == "output-denied"}
              name="circle-x"
              class="size-4 text-orange-600"
            />
            <LiveShadcn.Icon.icon
              :if={@state == "output-error"}
              name="circle-x"
              class="size-4 text-red-600"
            />
            {Map.get(
              %{
                "approval-requested" => "Awaiting Approval",
                "approval-responded" => "Responded",
                "input-available" => "Running",
                "input-streaming" => "Pending",
                "output-available" => "Completed",
                "output-denied" => "Denied",
                "output-error" => "Error"
              },
              @state
            )}
          </span>
        </div>
        <LiveShadcn.Icon.icon
          name="chevron-down"
          class="size-4 text-muted-foreground transition-transform group-data-[state=open]:rotate-180"
        />
      </button>
      <div
        data-slot="collapsible-content"
        id={Disclosure.panel_id(@id)}
        role="region"
        aria-labelledby={Disclosure.trigger_id(@id)}
        hidden={not @open}
        phx-hook={Disclosure.hook()}
        phx-mounted={Disclosure.owned_attributes(:panel)}
        data-lb-height-var="--collapsible-panel-height"
        data-lb-width-var="--collapsible-panel-width"
        data-open={flag(@open)}
        data-closed={flag(not @open)}
        class={[
          "data-[state=closed]:fade-out-0 data-[state=closed]:slide-out-to-top-2 data-[state=open]:slide-in-from-top-2 space-y-4 p-4 text-popover-foreground outline-none data-[state=closed]:animate-out data-[state=open]:animate-in",
          @content_class
        ]}
      >
        {render_slot(@inner_block)}
      </div>
    </div>
    """
  end

  # A disabled disclosure ignores interaction. `aria-disabled` and
  # `pointer-events-none` say so to a reader and to a mouse, but a keypress
  # on a focused trigger reaches neither, so the command itself is withheld.
  defp interactive(false, command), do: command
  defp interactive(_disabled, _command), do: nil

  # An HTML attribute with no value, or no attribute at all. Base UI marks
  # state by presence, so `data-open=""` and a missing `data-open` are the
  # two states a shadcn class string distinguishes.
  defp flag(true), do: ""
  defp flag(_state), do: nil

  # The variant tables, from the `cva` calls upstream writes them in.
  @variants %{
    "badgeVariants" => %{
      "variant" => %{
        "default" => "cn-badge-variant-default",
        "destructive" => "cn-badge-variant-destructive",
        "ghost" => "cn-badge-variant-ghost",
        "link" => "cn-badge-variant-link",
        "outline" => "cn-badge-variant-outline",
        "secondary" => "cn-badge-variant-secondary"
      }
    }
  }

  defp variant_class(table, group, value), do: get_in(@variants, [table, group, value])
end
