defmodule LiveAiElements.Components.Transcription do
  @moduledoc """
  Transcription.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/transcription.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `transcription` part."
  attr(:current_time, :any, default: nil)
  attr(:segments, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:children)
  slot(:inner_block)

  def transcription(assigns) do
    ~H"""
    <div
      data-slot={@rest[:"data-slot"] || "transcription"}
      class={["flex flex-wrap gap-1 text-sm leading-relaxed", @class]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {render_slot(@children)}
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `transcription-segment` part."
  attr(:index, :any, default: nil)
  attr(:is_active, :string, default: nil)
  attr(:is_past, :string, default: nil)
  attr(:segment, :any, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot", "type", "value", "name", "formaction"])
  slot(:inner_block)

  def transcription_segment(assigns) do
    ~H"""
    <button
      data-slot={@rest[:"data-slot"] || "transcription-segment"}
      data-active={@is_active}
      data-index={@index}
      type="button"
      class={[
        "inline text-left",
        if(@is_active, do: "text-primary", else: nil),
        if(@is_past, do: "text-muted-foreground", else: nil),
        if(!(@is_active || @is_past), do: "text-muted-foreground/60", else: nil),
        "cursor-pointer hover:text-foreground",
        if(!true, do: "cursor-default", else: nil),
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    >
      {@segment.text}
      {render_slot(@inner_block)}
    </button>
    """
  end
end
