defmodule LiveAiElements.Components.WebPreview do
  @moduledoc """
  Web preview. Built on `shadcn/input`.

  Upstream exports 2 more parts, and every one of them is a
  thin wrapper around a part of `<.tooltip>`, `<.collapsible>`. That component is one
  function here — its parts have to agree about which one they belong to,
  and an id repeated is an id to mistype — so it is what to compose inside
  this, and there is nothing for the wrappers to wrap.

  Generated by `mix ui.gen` from `registry/spec/ai_elements/web-preview.json`. Every
  class string and every `data-slot` below came from upstream. Change the
  spec or the recipe, not this file.
  """

  use Phoenix.Component

  @doc "The `web_preview` part."
  attr(:default_url, :string, default: "")
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def web_preview(assigns) do
    ~H"""
    <div class={["flex size-full flex-col rounded-lg border bg-card", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `web_preview_navigation` part."

  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def web_preview_navigation(assigns) do
    ~H"""
    <div class={["flex items-center gap-1 border-b p-2", @class]} {@rest}>
      {render_slot(@inner_block)}
    </div>
    """
  end

  @doc "The `input` part."
  attr(:input_value, :string, default: nil)
  attr(:type, :string, default: nil)
  attr(:value, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")

  attr(:rest, :global,
    include: [
      "data-slot",
      "type",
      "name",
      "value",
      "placeholder",
      "checked",
      "min",
      "max",
      "step",
      "minlength",
      "maxlength",
      "pattern",
      "readonly",
      "multiple",
      "autocomplete"
    ]
  )

  def web_preview_url(assigns) do
    ~H"""
    <input
      data-slot={@rest[:"data-slot"] || "input"}
      type={@type}
      placeholder="Enter URL..."
      value={@value || @input_value}
      class={[
        "cn-input w-full min-w-0 outline-none file:inline-flex file:border-0 file:bg-transparent file:text-foreground placeholder:text-muted-foreground disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 h-8 flex-1 text-sm",
        @class
      ]}
      {Map.drop(@rest, [:"data-slot"])}
    />
    """
  end

  @doc "The `web_preview_body` part."
  attr(:loading, :string, default: nil)
  attr(:src, :string, default: nil)
  attr(:url, :string, default: nil)
  attr(:class, :any, default: nil, doc: "Appended to the class string upstream renders.")
  attr(:rest, :global, include: ["data-slot"])
  slot(:inner_block)

  def web_preview_body(assigns) do
    ~H"""
    <div class="flex-1">
      <iframe
        sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-presentation"
        src={@src || @url || nil}
        title="Preview"
        class={["size-full", @class]}
        {@rest}
      >
        {render_slot(@inner_block)}
      </iframe>
      {@loading}
    </div>
    """
  end
end
